// Static English translations for Tunisian civil-service ministry and grade codes.
// Source: dim_etablissement (ministries) and dim_grade (grades) tables.
// Used by ForecastComponent when currentLang === 'en'.

export const EN_MINISTRIES: Record<string, string> = {
  R00: 'Ministry of Education',
  H00: 'Ministry of Health',
  S00: 'Ministry of Higher Education and Scientific Research',
  F00: 'Ministry of Interior',
};

export const EN_GRADES: Record<string, string> = {
  // ── 001 – 009 ────────────────────────────────────────────────────────────
  '001': 'Adjutant 2nd Class – Navy',
  '002': 'Counselor – Music Education',
  '003': 'Master of Conferences (Agric. Univ. Hosp. – Vet. Med.)',
  '004': 'Adjutant 1st Class – Navy',
  '005': 'Director of Agricultural Research',
  '006': 'Agricultural Research Attaché',
  '007': 'Technical Assistant',
  '008': 'Agricultural Research Officer',
  '009': 'Technical Assistant – Foreign Affairs',
  // ── 00A – 00Z ────────────────────────────────────────────────────────────
  '00A': 'Technical Assistant – Teaching',
  '00B': 'Technical Assistant – Statistics',
  '00C': 'Assistant (Univ. Hosp. – Vet. Med.)',
  '00D': 'Research Master – Agriculture',
  '00E': 'Inspector – Music Education',
  '00F': 'Chief Warrant Officer Sc. 1',
  '00G': 'Chief Warrant Officer Sc. 2',
  '00H': 'Chief Warrant Officer Sc. 3',
  '00I': 'Chief Warrant Officer – National Guard',
  '00J': 'Chief Warrant Officer – Civil Protection',
  '00K': 'Warrant Officer – Customs Brigade',
  '00L': 'Warrant Officer Sc. 1',
  '00M': 'Warrant Officer Sc. 2',
  '00N': 'Warrant Officer Sc. 3',
  '00O': 'Delegate',
  '00P': 'Vice Admiral of the Fleet',
  '00Q': 'Warrant Officer – National Guard',
  '00R': 'Warrant Officer – Civil Protection',
  '00S': 'Administrator',
  '00T': 'Controller General – Prime Minister',
  '00U': 'Deputy Controller General – PM',
  '00V': 'Principal Social Worker',
  '00W': 'Senior Controller',
  '00X': 'Deputy Senior Controller',
  '00Y': 'Senior Administrator',
  '00Z': 'Vice Admiral',
  // ── 010 – 01Z ────────────────────────────────────────────────────────────
  '010': 'Rear Admiral',
  '011': 'Chief Administrator',
  '012': 'Colonel Major',
  '013': 'Colonel Major – Navy',
  '014': 'Administrator General',
  '015': 'Captain of the Ship',
  '016': 'Frigate Captain',
  '017': 'Principal Administrator',
  '018': 'Corvette Captain',
  '019': 'Corporal – Civil Protection',
  '01A': 'Principal Administrator – Social Affairs',
  '01B': 'Inspector General – Customs Brigade',
  '01C': 'Colonel – Customs Brigade',
  '01D': 'Principal Administrator – Public Services',
  '01E': 'Lieutenant Colonel – Customs Brigade',
  '01F': 'Attaché – Customs Brigade',
  '01G': 'Administrator – Public Services',
  '01H': 'Controller – Customs Brigade',
  '01I': 'Principal Preacher',
  '01J': 'Revenue Agent',
  '01K': 'Revenue Agent – Property Tax',
  '01L': 'Sports Supervisor (temporary)',
  '01M': 'Lieutenant of the Ship',
  '01N': 'Ensign 1st Class',
  '01P': 'Communications Clerk',
  '01Q': 'Ensign 2nd Class',
  '01R': 'Warrant Officer Major',
  '01S': 'Technical Police Officer',
  '01T': 'Administrator – Court Registry',
  '01U': 'Principal Registrar',
  '01V': 'Registrar',
  '01W': 'Captain A1',
  '01X': 'Principal Petty Officer Sc. 2',
  '01Y': 'Technical Agent',
  '01Z': 'Principal Petty Officer Sc. 3',
  // ── 020 – 02Z ────────────────────────────────────────────────────────────
  '020': 'First Petty Officer Sc. 2',
  '021': 'Technical Agent – Teaching',
  '022': 'First Petty Officer Sc. 3',
  '023': 'Warrant Officer Major – Navy',
  '024': 'Technical Agent – Statistics',
  '025': 'Principal Petty Officer Sc. 1',
  '026': 'First Petty Officer Sc. 1',
  '027': 'Library Assistant',
  '028': 'Actor 1st Category',
  '029': 'Actor 2nd Category',
  '02A': 'Library Assistant',
  '02B': 'Conciliator General',
  '02C': 'Chief Conciliator',
  '02D': 'Conciliator',
  '02E': 'Sergeant Major / Petty Officer Sc. 1',
  '02F': 'Second Petty Officer 1st Class Sc. 1',
  '02G': 'Archive Assistant',
  '02H': 'Second Petty Officer 2nd Class Sc. 1',
  '02I': 'Private 1st Class',
  '02J': 'Laboratory Assistant',
  '02K': 'Private (ADL)',
  '02L': 'Analyst',
  '02M': 'Principal Analyst',
  '02N': 'Quartermaster 1st Class',
  '02P': 'Social Animator',
  '02Q': 'Quartermaster 2nd Class',
  '02R': 'Animator',
  '02S': 'Seaman 1st Class',
  '02T': 'Application Animator',
  '02U': 'Seaman (ADL)',
  '02V': 'Kindergarten Animator',
  '02W': 'Biologist',
  '02X': 'Principal Biologist',
  '02Y': 'Deputy Biologist',
  '02Z': 'Sergeant Major / Petty Officer Sc. 2',
  // ── 030 – 03Z ────────────────────────────────────────────────────────────
  '030': 'Sergeant Major / Petty Officer Sc. 3',
  '031': 'Architect',
  '032': 'Second Petty Officer 1st Class Sc. 2',
  '033': 'Second Petty Officer 1st Class Sc. 3',
  '034': 'Divisional Architect',
  '035': 'Second Petty Officer 2nd Class Sc. 2',
  '036': 'Second Petty Officer 2nd Class Sc. 3',
  '037': 'Chief Architect',
  '038': 'Architect General',
  '039': 'Principal Architect',
  '03A': 'Musician 1st Category',
  '03B': 'Chorister 1st Category',
  '03C': 'Aspirant',
  '03D': 'Musician 2nd Category',
  '03E': 'Chorister 2nd Category',
  '03F': 'Assistant – Higher Education',
  '03G': 'Assistant – Higher Agricultural Education',
  '03H': 'Musician 3rd Category',
  '03I': 'Camera Assistant',
  '03J': 'Corporal Chef – Civil Protection',
  '03K': 'Master – Music Education',
  '03L': 'Professor – Music Education',
  '03M': 'Decorator Assistant',
  '03N': 'Assistant (Univ. Hosp. – Medicine)',
  '03O': 'Corporal Major – Civil Protection',
  '03P': 'Deputy Delegate',
  '03Q': 'Music Professor – 1st Cycle',
  '03R': 'Supervisor',
  '03S': 'Principal Music Professor',
  '03T': 'Assistant 2nd Category',
  '03U': 'Chorister 3rd Category',
  '03V': 'Actor 3rd Category',
  '03W': 'Principal Director Secretary',
  '03X': 'Director Secretary 1st Class',
  '03Y': 'Stenographer Secretary',
  '03Z': 'Senior Administrator – Public Services',
  // ── 040 – 04Z ────────────────────────────────────────────────────────────
  '040': 'General Supervisor 1st Class',
  '041': 'Supervisor',
  '042': 'Principal Supervisor',
  '043': 'Preparer',
  '044': 'Principal Lab Technician',
  '045': 'Intern – Veterinary Medicine',
  '046': 'Master Apprentice – General Education',
  '047': 'Editing Assistant',
  '048': 'Assistant (Univ. Hosp. – Dental Medicine)',
  '049': 'Assistant (Univ. Hosp. – Pharmacy)',
  '04A': 'Production Assistant',
  '04B': 'Management Attaché',
  '04C': 'Counselor – Administrative Tribunal',
  '04D': 'Deputy Social Worker',
  '04E': 'Master Apprentice – Manual Education',
  '04F': 'Master – General Education',
  '04G': 'Administrative Attaché',
  '04H': 'Master – Manual Education',
  '04I': 'Administrator General – Social Services',
  '04J': 'Attaché – Foreign Affairs',
  '04K': 'Chief Social Worker',
  '04L': 'Social Worker Counselor',
  '04M': 'Cipher Attaché – Foreign Affairs',
  '04N': 'Administrator General – Public Services',
  '04P': 'Attaché Inspector – Property Tax',
  '04Q': 'Chief Administrator – Public Services',
  '04R': 'Attaché – Public Health',
  '04S': 'Cultural Attaché',
  '04T': 'Administrative Secretary – Public Services',
  '04U': 'Public Health Clerk',
  '04V': 'Public Health Reception Agent',
  '04W': 'Secondary Education Temporary Agent',
  '04X': 'Primary Education Temporary Agent',
  '04Y': 'Attaché Inspector – Economic Affairs',
  '04Z': 'Senior Administrator – Court Registry',
  // ── 050 – 05Z ────────────────────────────────────────────────────────────
  '050': 'Deputy Registrar – Courts',
  '051': 'Attaché Inspector – Financial Affairs',
  '052': 'Attaché Inspector – Commerce',
  '053': 'Attaché Inspector – Financial Services',
  '054': 'Attaché Inspector – Labour',
  '055': 'Imam Orator',
  '056': 'Religious Affairs Inspector',
  '057': 'Supply Attaché',
  '058': 'Imam – 5 Prayers Mosque',
  '059': 'Imam – 5 Prayers Prayer Hall',
  '05A': 'Press Attaché',
  '05B': 'Muezzin – Mosques',
  '05C': 'Muezzin – Prayer Halls',
  '05D': 'Archaeological Research Attaché',
  '05E': 'Mosque Maintenance Officer',
  '05F': 'Research Attaché 2nd Category',
  '05G': 'Social Worker',
  '05H': 'Public Health Auxiliary',
  '05I': 'Prayer Hall Maintenance Officer',
  '05J': 'Clerk – Customs Brigade',
  '05K': 'Deputy Child Protection Delegate',
  '05L': 'Domestic Educator',
  '05M': 'Penitentiary Services Auxiliary',
  '05N': 'Librarian',
  '05O': 'Foreign Affairs Secretary (in training)',
  '05P': 'Archivist',
  '05Q': 'Deputy Librarian',
  '05R': 'Deputy Archivist',
  '05S': 'Principal Librarian',
  '05T': 'Principal Archivist',
  '05U': 'Hadith Narrator',
  '05V': 'Librarian / Documentalist',
  '05W': 'Deputy Documentalist',
  '05X': 'Muaddeb (Religious Educator)',
  '05Y': 'Principal Documentalist',
  '05Z': 'General Supervisor',
  // ── 060 – 06Z ────────────────────────────────────────────────────────────
  '060': 'Mosque Supervisor',
  '061': 'Brigadier – Customs Brigade',
  '062': 'Ablution Room Supervisor',
  '063': 'Quran Reader',
  '064': 'Brigadier Chief',
  '065': 'Narrator Imam',
  '066': 'Educator Narrator Imam',
  '067': 'Muezzin Supervisor',
  '068': 'Narrator Muezzin Imam',
  '069': 'Maintenance Muezzin',
  '06A': 'Brigadier',
  '06B': 'Maintenance Narrator Muezzin',
  '06C': 'Imam Muezzin Muaddeb',
  '06D': 'Cameraman',
  '06E': 'Imam Muaddeb',
  '06F': 'Narrator Muaddeb Imam',
  '06G': 'Cameraman',
  '06H': 'Mosque Muezzin Imam',
  '06I': 'Educator Narrator',
  '06J': 'Captain A2',
  '06K': 'Captain – Customs Brigade',
  '06L': 'Captain – National Guard',
  '06M': 'Captain – Civil Protection',
  '06N': 'Corporal',
  '06O': 'Corporal Chief',
  '06P': 'Archaeological Research Officer',
  '06Q': 'Imam 5 Orator',
  '06R': 'Research Officer 2nd Category',
  '06S': 'Imam 5 Educator',
  '06T': 'Educator Imam 5 Muezzin',
  '06U': 'Muezzin Muaddeb',
  '06V': 'Laboratory Head',
  '06W': 'Five-Prayer Imam Muezzin',
  '06X': 'Muaddeb Supervisor',
  '06Y': 'Chief Laboratory Head',
  '06Z': 'Controller General – DEAF',
  // ── 070 – 07Z ────────────────────────────────────────────────────────────
  '070': 'Chief Controller – DEAF',
  '071': 'General Laboratory Head',
  '072': 'Controller – DEAF',
  '073': 'Deputy Controller – DEAF',
  '074': 'Chief Editor',
  '075': 'Court Bailiff',
  '076': 'Supply Teacher 1',
  '077': 'Supply Teacher 2',
  '078': 'Supervisory Agent',
  '079': 'Regulatory Inspector Attaché',
  '07A': 'Dental Surgeon – Public Health',
  '07B': 'Principal Dental Surgeon – PH',
  '07C': 'Major Dental Surgeon',
  '07D': 'Specialist Dental Surgeon',
  '07E': 'Principal Specialist Dental Surgeon',
  '07F': 'Major Specialist Dental Surgeon',
  '07G': 'Head of Works – 1st Cycle',
  '07H': 'Head of Works 2nd Category',
  '07I': 'Head of Works 2nd Cat. – Agriculture',
  '07J': 'Head of Works – Laboratory',
  '07K': 'Municipal Regulatory Controller',
  '07L': 'Municipal Regulatory Supervisor',
  '07M': 'Deputy Lab Head of Works',
  '07N': 'Municipal Regulatory Inspector',
  '07P': 'Divisional Lab Head of Works',
  '07R': 'Specialist Dental Surgeon (temp.)',
  '07S': 'General Corps – University Hospital Medicine',
  '07T': 'Major General – University Hospital Medicine',
  '07U': 'Brigadier General – University Hospital Medicine',
  '07V': 'Principal Dental Surgeon',
  '07W': 'Dental Surgeon – Health Service',
  '07X': 'Temporary Dental Surgeon – PH',
  '07Y': 'Specialist Dental Surgeon',
  '07Z': 'Principal Specialist Dental Surgeon',
  // ── 080 – 08Z ────────────────────────────────────────────────────────────
  '080': 'Lieutenant – Customs',
  '081': 'Chorister 2nd Category',
  '082': 'Trainee Chorister 2nd Year',
  '083': 'Trainee Dancer 2nd Year',
  '084': 'Chorister 1st Category',
  '085': 'Colonel Major – University Hospital Medicine',
  '086': 'Colonel – University Hospital Medicine',
  '087': 'Trainee Chorister 1st Year',
  '088': 'Lieutenant Colonel – University Hospital Medicine',
  '089': 'Trainee Dancer 1st Year',
  '08A': 'Hairdresser / Make-up Artist',
  '08B': 'Dancer 1st Category',
  '08C': 'Dancer 2nd Category',
  '08D': 'Colonel',
  '08E': 'Troop Administrator',
  '08F': 'Colonel – National Guard',
  '08G': 'Colonel – Civil Protection',
  '08H': 'Commander (Major)',
  '08I': 'Commander – University Hospital Medicine',
  '08J': 'Commander – Customs Brigade',
  '08K': 'Captain – University Hospital Medicine',
  '08L': 'Lieutenant – University Hospital Medicine',
  '08M': 'Colonel – Penitentiary Services',
  '08N': 'General Corps – University Hospital Pharmacy',
  '08O': 'Colonel Major – Civil Protection',
  '08P': 'Commander – National Guard',
  '08Q': 'Major General – University Hospital Pharmacy',
  '08R': 'Brigadier General – University Hospital Pharmacy',
  '08S': 'New Technologies Technical Expert',
  '08T': 'Colonel Major – University Hospital Pharmacy',
  '08U': 'Colonel – University Hospital Pharmacy',
  '08V': 'Principal Commander',
  '08W': 'Lieutenant Colonel – University Hospital Pharmacy',
  '08X': 'Commander – University Hospital Pharmacy',
  '08Y': 'Lieutenant Colonel – Penitentiary Services',
  '08Z': 'Commander – Civil Protection',
  // ── 090 – 09Z ────────────────────────────────────────────────────────────
  '090': 'Deputy Chief – Customs',
  '091': 'Commander – Penitentiary Services',
  '092': 'Documentation Clerk',
  '093': 'Archive Clerk',
  '094': 'Administrative Clerk',
  '095': 'Counselor – Agricultural Primary Education',
  '096': 'Principal Professor – Dramatic Arts',
  '097': 'Library Clerk',
  '098': 'Counselor – Dramatic Arts Education',
  '099': 'Professor – Dramatic Arts Education',
  '09A': 'Police Commissioner General 2nd Class',
  '09B': 'Professor – Dramatic Arts 1st Class',
  '09C': 'Counselor Supervisor',
  '09D': 'Police Commissioner General 1st Class',
  '09E': 'Stage Manager',
  '09F': 'Police Commissioner',
  '09G': 'Principal Police Commissioner',
  '09H': 'Principal Wardrobe Mistress',
  '09I': 'Wardrobe Mistress',
  '09J': 'Senior Class Police Commissioner',
  '09K': 'Counselor – Court of Accounts',
  '09L': 'Deputy Counselor – Court of Accounts',
  '09M': 'Counselor – Foreign Affairs',
  '09N': 'General Culture Counselor',
  '09P': 'Cultural Counselor',
  '09Q': 'Chief Cultural Counselor',
  '09R': 'Cultural Clerk',
  '09S': 'Social Education Counselor',
  '09T': 'Cultural Agent',
  '09U': 'Captain – University Hospital Pharmacy',
  '09V': 'Arts Education Counselor',
  '09W': 'Counselor – Public Services',
  '09X': 'Ballet Master',
  '09Y': 'Counselor – Primary Education',
  '09Z': 'Deputy Ballet Master',
  // ── 0A1 – 0AZ ────────────────────────────────────────────────────────────
  '0A1': 'Pedagogical Counselor – Physical Education',
  '0A2': 'Orchestra Conductor',
  '0A3': 'Chorale Director',
  '0A4': 'Press Counselor',
  '0A5': 'Revenue Agent – Economic Affairs',
  '0A6': 'Chief Press Counselor',
  '0A7': 'Deputy Museum Conservator',
  '0A8': 'Press Counselor General',
  '0A9': 'Economic Affairs Agent',
  '0AA': 'Library / Documentation Conservator',
  '0AB': 'Administrator – Foreign Affairs',
  '0AC': 'Administrative Attaché – FA',
  '0AD': 'Chief Library / Documentation Conservator',
  '0AE': 'Clerk – Foreign Affairs',
  '0AF': 'Reception Agent – FA',
  '0AG': 'Chief Museum Conservator',
  '0AH': 'Administrative Secretary – FA',
  '0AI': 'Central Financial Inspector – FA',
  '0AJ': 'General Library / Documentation Counselor',
  '0AK': 'Financial Inspector – FA',
  '0AL': 'Financial Attaché – FA',
  '0AM': 'Museum Conservator',
  '0AN': 'Financial Controller – FA',
  '0AP': 'Controller',
  '0AQ': 'Principal Petty Officer',
  '0AR': 'Lieutenant – University Hospital Pharmacy',
  '0AS': 'Economic Affairs Controller',
  '0AT': 'Financial Controller General',
  '0AU': 'Financial Controller 1st Class',
  '0AV': 'Property Affairs Controller',
  '0AW': 'Controller 2nd Class',
  '0AX': 'Controller 3rd Class',
  '0AY': 'Property Controller',
  '0AZ': 'General Corps – University Hospital Dentistry',
  // ── 0B0 – 0BZ ────────────────────────────────────────────────────────────
  '0B0': 'Senior Technical Police Officer',
  '0B1': 'Data Processing Controller',
  '0B2': 'Major General – University Hospital Dentistry',
  '0B3': 'Communications Controller',
  '0B4': 'Labour Controller',
  '0B5': 'Brigadier General – University Hospital Dentistry',
  '0B6': 'Colonel Major – University Hospital Dentistry',
  '0B7': 'Diplomatic Courier',
  '0B8': 'Financial Services Controller',
  '0B9': 'Colonel – University Hospital Dentistry',
  '0BA': 'Principal Diplomatic Courier',
  '0BB': 'Lieutenant Colonel – University Hospital Dentistry',
  '0BC': 'Commander – University Hospital Dentistry',
  '0BD': 'Typist',
  '0BE': 'General Reporter Counselor',
  '0BF': 'Chief Reporter Counselor',
  '0BG': 'Reporter Counselor',
  '0BH': 'Deputy Reporter Counselor',
  '0BI': 'Sports Animator',
  '0BJ': 'Captain – University Hospital Dentistry',
  '0BK': 'Lieutenant – University Hospital Dentistry',
  '0BL': 'Justice Auditor',
  '0BM': 'Principal Professor – Physical Education',
  '0BN': 'Temporary Student Cat. A2',
  '0BP': 'Decorator',
  '0BQ': 'Temporary Student Cat. A3',
  '0BR': 'Administrator General – State Domains',
  '0BS': 'Chief Administrator – State Domains',
  '0BT': 'Senior Administrator – State Domains',
  '0BU': 'Administrator – State Domains',
  '0BV': 'Administrative Attaché – Domains',
  '0BW': 'Administrative Secretary – Domains',
  '0BX': 'Clerk – State Domains',
  '0BY': 'Second Assistant Director',
  '0BZ': 'Domains Agent',
  // ── 0C1 – 0CZ ────────────────────────────────────────────────────────────
  '0C1': 'Second Secretary – Film Production',
  '0C2': 'General Corps – University Hospital Medicine (Prof.)',
  '0C3': 'Public Expenditure Controller',
  '0C4': 'Photography Director',
  '0C5': 'Deputy Public Expenditure Controller',
  '0C6': 'Major General – University Hospital Medicine (Prof.)',
  '0C7': 'Director of Archaeological Research',
  '0C8': 'Brigadier General – University Hospital Medicine (Prof.)',
  '0C9': 'Colonel Major – University Hospital Medicine (Prof.)',
  '0CA': 'Colonel – University Hospital Medicine (Prof.)',
  '0CB': 'Lieutenant Colonel – University Hospital Medicine (Prof.)',
  '0CC': 'Commander – University Hospital Medicine (Prof.)',
  '0CD': 'Captain – University Hospital Medicine (Prof.)',
  '0CE': 'General Corps – University Hospital Pharmacy (Prof.)',
  '0CF': 'Major General – University Hospital Pharmacy (Prof.)',
  '0CG': 'Bursar',
  '0CH': 'Brigadier General – University Hospital Pharmacy (Prof.)',
  '0CI': 'Colonel Major – University Hospital Pharmacy (Prof.)',
  '0CJ': 'Colonel – University Hospital Pharmacy (Prof.)',
  '0CK': 'Listener-Typist',
  '0CL': 'Lieutenant Colonel – University Hospital Pharmacy (Prof.)',
  '0CM': 'Educator',
  '0CN': 'Commander – University Hospital Pharmacy (Prof.)',
  '0CP': 'Group Educator',
  '0CQ': 'Military Assistant Professor',
  '0CR': 'Corporal Chief – Prisons',
  '0CS': 'Captain – University Hospital Pharmacy (Prof.)',
  '0CT': 'Postman / Factor',
  '0CU': 'Corporal – Prisons',
  '0CV': 'Brigadier General',
  '0CW': 'General of the Army Corps',
  '0CX': 'Major General',
  '0CY': 'Security Guard',
  '0CZ': 'General Corps – University Hospital Dentistry (Prof.)',
  // ── 0D1 – 0DZ ────────────────────────────────────────────────────────────
  '0D1': 'Major General – University Hospital Dentistry (Prof.)',
  '0D2': 'Geologist General',
  '0D3': 'Chief Geologist',
  '0D4': 'Court Registrar',
  '0D5': 'Principal Geologist',
  '0D6': 'Divisional Geologist',
  '0D7': 'Brigadier General – University Hospital Dentistry (Prof.)',
  '0D8': 'Geologist',
  '0D9': 'Deputy Geologist',
  '0DA': 'Colonel Major – University Hospital Dentistry (Prof.)',
  '0DB': 'Kindergarten Apprentice Animator',
  '0DC': 'Colonel – University Hospital Dentistry (Prof.)',
  '0DD': 'Lieutenant Colonel – University Hospital Dentistry (Prof.)',
  '0DE': 'Sound Illustrator',
  '0DF': 'Commander – University Hospital Dentistry (Prof.)',
  '0DG': 'Reception Agent',
  '0DH': 'Deputy Typist',
  '0DI': 'Captain – University Hospital Dentistry (Prof.)',
  '0DJ': 'General Corps – University Hospital Veterinary Medicine (Prof.)',
  '0DK': 'Major General – University Hospital Vet. Med. (Prof.)',
  '0DL': 'Major Nurse – Public Health',
  '0DM': 'Nurse – Public Health',
  '0DN': 'Brigadier General – University Hospital Vet. Med. (Prof.)',
  '0DP': 'Specialized Nurse',
  '0DQ': 'Principal Nurse – PH',
  '0DR': 'Colonel Major – University Hospital Vet. Med. (Prof.)',
  '0DS': 'Deputy Engineer',
  '0DT': 'Deputy Engineer – Foreign Affairs',
  '0DU': 'Colonel – University Hospital Vet. Med. (Prof.)',
  '0DV': 'Deputy Engineer – Teaching',
  '0DW': 'Professor – Physical Education (Higher Class)',
  '0DX': 'Lieutenant Colonel – University Hospital Vet. Med. (Prof.)',
  '0DY': 'Deputy Engineer – Statistics',
  '0DZ': 'Commander – University Hospital Vet. Med. (Prof.)',
  // ── 0E1 – 0EZ ────────────────────────────────────────────────────────────
  '0E1': 'Divisional Engineer',
  '0E2': 'Captain – University Hospital Vet. Med. (Prof.)',
  '0E3': 'Engineer – Foreign Affairs',
  '0E4': 'Divisional Engineer – Statistics & Economics',
  '0E5': 'General Corps – University Hospital Master of Conferences',
  '0E6': 'Major General – University Hospital Master of Conferences',
  '0E7': 'Chief Engineer',
  '0E8': 'Brigadier General – University Hospital Master of Conferences',
  '0E9': 'Colonel Major – University Hospital Master of Conferences',
  '0EA': 'Chief Engineer – Statistics & Economics',
  '0EB': 'Lieutenant Colonel – University Hospital Master of Conferences',
  '0EC': 'Commander – University Hospital Master of Conferences',
  '0ED': 'Engineer General',
  '0EE': 'Chief Administrator – Registry',
  '0EF': 'Captain – University Hospital Master of Conferences',
  '0EG': 'Engineer General – Statistics',
  '0EH': 'General Corps – University Hospital Pharmacy (MCA)',
  '0EI': 'Major General – University Hospital Pharmacy (MCA)',
  '0EJ': 'Computer Engineer',
  '0EK': 'Brigadier General – University Hospital Pharmacy (MCA)',
  '0EL': 'Pedagogical Counselor – Youth and Childhood',
  '0EM': 'Principal Engineer',
  '0EN': 'Principal Engineer – Foreign Affairs',
  '0EP': 'Principal Engineer – Teaching',
  '0EQ': 'Colonel Major – University Hospital Pharmacy (MCA)',
  '0ER': 'Colonel – University Hospital Pharmacy (MCA)',
  '0ES': 'Principal Engineer – Statistics & Economics',
  '0ET': 'Lieutenant Colonel – University Hospital Pharmacy (MCA)',
  '0EU': 'Commander – University Hospital Pharmacy (MCA)',
  '0EV': 'Works Engineer',
  '0EW': 'Professor – Physical Education (Senior)',
  '0EX': 'Captain – University Hospital Pharmacy (MCA)',
  '0EY': 'Works Engineer – Teaching',
  '0EZ': 'General Corps – University Hospital Dentistry (MCA)',
  // ── 0F1 – 0FZ ────────────────────────────────────────────────────────────
  '0F1': 'Works Engineer – Statistics & Economics',
  '0F2': 'Major General – University Hospital Dentistry (MCA)',
  '0F3': 'Brigadier General – University Hospital Dentistry (MCA)',
  '0F4': 'Colonel Major – University Hospital Dentistry (MCA)',
  '0F5': 'Colonel – University Hospital Dentistry (MCA)',
  '0F6': 'Lieutenant Colonel – University Hospital Dentistry (MCA)',
  '0F7': 'Commander – University Hospital Dentistry (MCA)',
  '0F8': 'Captain – University Hospital Dentistry (MCA)',
  '0F9': 'General Corps – University Hospital Vet. Med. (MC)',
  '0FA': 'Deputy Inspector – Historical Monuments',
  '0FB': 'Major General – University Hospital Vet. Med. (MC)',
  '0FC': 'Brigadier General – University Hospital Vet. Med. (MC)',
  '0FD': 'Property Affairs Inspector',
  '0FE': 'Colonel Major – University Hospital Vet. Med. (MC)',
  '0FF': 'Economic Affairs Inspector',
  '0FG': 'Omda (Local Chief)',
  '0FH': 'Colonel – University Hospital Vet. Med. (MC)',
  '0FI': 'Lieutenant Colonel – University Hospital Vet. Med. (MC)',
  '0FJ': 'Commander – University Hospital Vet. Med. (MC)',
  '0FK': 'Central Communications Inspector',
  '0FL': 'Captain – University Hospital Vet. Med. (MC)',
  '0FM': 'Central Economic Affairs Inspector',
  '0FN': 'Central Financial Services Inspector',
  '0FP': 'General Corps – University Hospital Assistants',
  '0FQ': 'Major General – University Hospital Assistants',
  '0FR': 'Central Property Inspector',
  '0FS': 'Cipher Inspector – FA',
  '0FT': 'Central Cipher Inspector – FA',
  '0FU': 'Brigadier General – University Hospital Assistants',
  '0FV': 'Property Tax Inspector',
  '0FW': 'Property Agent',
  '0FX': 'Central Labour Inspector',
  '0FY': 'Divisional Inspector – Public Health',
  '0FZ': 'Colonel Major – University Hospital Assistants',
  // ── 0G1 – 0GZ ────────────────────────────────────────────────────────────
  '0G1': 'Social Education Inspector',
  '0G2': 'Colonel – University Hospital Assistants',
  '0G3': 'Lieutenant Colonel – University Hospital Assistants',
  '0G4': 'Commander – University Hospital Assistants',
  '0G5': 'Chief Communications Inspector',
  '0G6': 'Captain – University Hospital Assistants',
  '0G7': 'Chief Economic Affairs Inspector',
  '0G8': 'General Corps – University Hospital Pharmacy (Assistant)',
  '0G9': 'Chief Financial Services Inspector',
  '0GA': 'Chief Labour Inspector',
  '0GB': 'Major General – University Hospital Pharmacy (Assistant)',
  '0GC': 'Brigadier General – University Hospital Pharmacy (Assistant)',
  '0GD': 'Agricultural Education Inspector',
  '0GE': 'Paramedical Education Inspector',
  '0GF': 'Colonel Major – University Hospital Pharmacy (Assistant)',
  '0GG': 'Arts Education Inspector',
  '0GH': 'Colonel – University Hospital Pharmacy (Assistant)',
  '0GI': 'Lieutenant Colonel – University Hospital Pharmacy (Assistant)',
  '0GJ': 'Primary Education Inspector',
  '0GK': 'Commander – University Hospital Pharmacy (Assistant)',
  '0GL': 'Inspector – 2nd Degree, Youth and Childhood',
  '0GM': 'Vocational Education Inspector',
  '0GN': 'Captain – University Hospital Pharmacy (Assistant)',
  '0GP': 'General Corps – University Hospital Dentistry (Assistant)',
  '0GQ': 'Colonel Major – National Guard',
  '0GR': 'Major General – University Hospital Dentistry (Assistant)',
  '0GS': 'General Secondary Education Inspector',
  '0GT': 'Brigadier General – University Hospital Dentistry (Assistant)',
  '0GU': 'Technical Secondary Education Inspector',
  '0GV': 'General Inspector – Public Health',
  '0GW': 'General Inspector – Property',
  '0GX': 'Chief Inspector – Property',
  '0GY': 'General Inspector – Economic Affairs',
  '0GZ': 'General Inspector – Education',
  // ── 0H1 – 0HZ ────────────────────────────────────────────────────────────
  '0H1': 'General Inspector – Agricultural Education',
  '0H2': 'General Inspector – Customs Office',
  '0H3': 'General Inspector – Financial Services',
  '0H4': 'Temporary Student Cat. A1',
  '0H5': 'General Inspector – Communications',
  '0H6': 'Chief Inspector – Customs Office',
  '0H7': 'General Inspector – Labour',
  '0H8': 'Central Inspector – Customs Office',
  '0H9': 'Inspector – Customs Office',
  '0HA': 'Inspector – 2nd Degree, Physical Education',
  '0HB': 'Attaché – Customs Office',
  '0HC': 'Controller – Customs Office',
  '0HD': 'Inspector – 1st Degree, Physical Education',
  '0HE': 'Clerk – Customs Office',
  '0HF': 'Colonel Major – University Hospital Dentistry (Assistant)',
  '0HG': 'Inspector – Historical Monuments',
  '0HI': 'Communications Inspector',
  '0HJ': 'Police Inspector',
  '0HK': 'Colonel – University Hospital Dentistry (Assistant)',
  '0HL': 'Lieutenant Colonel – University Hospital Dentistry (Assistant)',
  '0HM': 'Commander – University Hospital Dentistry (Assistant)',
  '0HN': 'Captain – University Hospital Dentistry (Assistant)',
  '0HP': 'Principal Inspector – Economic Affairs',
  '0HQ': 'Sports Professor',
  '0HR': 'General Corps – University Hospital Vet. Med. (Assistant)',
  '0HS': 'Principal Inspector – Property Affairs',
  '0HT': 'Principal Sports Apprentice Educator',
  '0HU': 'Major General – University Hospital Vet. Med. (Assistant)',
  '0HV': 'Principal Inspector – Cipher / FA',
  '0HW': 'Brigadier General – University Hospital Vet. Med. (Assistant)',
  '0HX': 'Colonel Major – University Hospital Vet. Med. (Assistant)',
  '0HY': 'Principal Inspector – Property Tax',
  '0HZ': 'Colonel – University Hospital Vet. Med. (Assistant)',
  // ── 0I1 – 0IZ ────────────────────────────────────────────────────────────
  '0I1': 'Principal Inspector – Agricultural Education',
  '0I2': 'Lieutenant Colonel – University Hospital Vet. Med. (Assistant)',
  '0I3': 'Commander – University Hospital Vet. Med. (Assistant)',
  '0I4': 'Principal Inspector – Vocational Education',
  '0I5': 'Captain – University Hospital Vet. Med. (Assistant)',
  '0I6': 'Professor Technologist',
  '0I7': 'Principal Inspector – Secondary Education',
  '0I8': 'Master Technologist',
  '0I9': 'Technologist',
  '0IA': 'Principal Inspector – Physical Education',
  '0IB': 'Principal Inspector – PTT (Post & Telecom)',
  '0IC': 'Principal Inspector – Financial Services',
  '0ID': 'Principal Inspector – Labour',
  '0IE': 'Basic Preparatory Student',
  '0IF': 'Active Officer Student 2nd Year',
  '0IG': 'Active Officer Student 3rd Year',
  '0IH': 'Active Officer Student 1st Year',
  '0II': 'Active Non-Commissioned Officer Student',
  '0IJ': 'Regional Inspector – Social Education',
  '0IK': 'Regional Inspector – Public Health',
  '0IL': 'Active Officer Student 4th Year',
  '0IM': 'Regional Inspector – Primary Education',
  '0IN': 'Financial Services Inspector',
  '0IP': 'Labour Inspector',
  '0IQ': 'Sports Application Educator',
  '0IR': 'Assistant Technologist',
  '0IS': 'Teacher / Master',
  '0IT': 'Social Education Teacher',
  '0IU': 'Chief Labour Medical Inspector',
  '0IV': 'Technical Instructor',
  '0IW': 'Divisional Labour Medical Inspector',
  '0IX': 'Regional Labour Medical Inspector',
  '0IY': 'School Principal',
  '0IZ': 'Labour Medical Inspector',
  // ── 0J1 – 0JZ ────────────────────────────────────────────────────────────
  '0J1': 'Reception Agent',
  '0J2': 'Colonel – University Hospital Master of Conferences',
  '0J3': 'General Inspector – Physical Education',
  '0J4': 'Journalist',
  '0J5': 'Principal Physical Education Master',
  '0J6': 'Captain – Magistrate 2nd Grade',
  '0J7': 'Principal Journalist',
  '0J8': 'Senior Administrator – Court of Accounts Registry',
  '0J9': 'Administrator – Court of Accounts Registry',
  '0JA': 'Reporter Journalist',
  '0JB': 'Lieutenant',
  '0JC': 'Lieutenant Colonel',
  '0JD': 'Lieutenant Colonel – National Guard',
  '0JE': 'Lieutenant Colonel – Civil Protection',
  '0JF': 'Lieutenant – National Guard',
  '0JG': 'Lieutenant – Civil Protection',
  '0JH': 'Lieutenant – Customs Brigade',
  '0JI': 'Magistrate 1st Grade',
  '0JJ': 'Magistrate 2nd Grade',
  '0JK': 'Magistrate 3rd Grade',
  '0JL': 'Pedagogical Inspector – Vocational Training',
  '0JM': 'Application Master',
  '0JN': 'Principal Registrar – Court of Accounts',
  '0JP': 'Master Assistant – Higher Education',
  '0JQ': 'Master Application – Physical Education',
  '0JR': 'Master Assistant – Agricultural Education',
  '0JS': 'Master Assistant – University Hospital',
  '0JT': 'Deputy Registrar – Court of Accounts',
  '0JU': 'Bailiff – Court of Accounts',
  '0JV': 'Auxiliary Master Cat. A',
  '0JW': 'Registrar – Court of Accounts',
  '0JX': 'Principal Counselor – IOSU',
  '0JY': 'Auxiliary Master Cat. B',
  '0JZ': 'Counselor – IOSU',
  // ── 0K1 – 0KZ ────────────────────────────────────────────────────────────
  '0K1': 'Auxiliary Master Cat. C',
  '0K2': 'Deputy Counselor – IOSU',
  '0K3': 'Telecom Supervisor',
  '0K4': 'Auxiliary Master Cat. D',
  '0K5': 'Post Supervisor',
  '0K6': 'Auditor',
  '0K7': 'Chief Telecom Operator',
  '0K8': 'General Inspector – Vocational Training',
  '0K9': 'Principal Exploitation Agent',
  '0KA': 'Telecom Operator',
  '0KB': 'General Counselor – IOSU',
  '0KC': 'Child Protection Delegate 3rd Grade',
  '0KD': 'Master of Conferences',
  '0KE': 'MCA – Dental Medicine',
  '0KF': 'MCA – University Hospital Pharmacy',
  '0KG': 'Child Protection Delegate 2nd Grade',
  '0KH': 'Child Protection Delegate 1st Grade',
  '0KI': 'General – Customs',
  '0KJ': 'Colonel Major – Customs',
  '0KK': 'Master of Conferences (Agric. Univ. Hosp. – Medicine)',
  '0KL': 'Colonel – Customs',
  '0KM': 'Lieutenant Colonel – Customs',
  '0KN': 'Commander – Customs',
  '0KO': 'Expert Counselor – Security Services',
  '0KP': 'Master of Conferences – Higher Agricultural Education',
  '0KQ': 'Master Scale I',
  '0KR': 'Master Scale II',
  '0KS': 'Master – Physical Education',
  '0KT': 'Master Scale III',
  '0KU': 'Captain – Customs',
  '0KV': 'Master – Arts Education',
  '0KW': 'Lieutenant Major – Customs',
  '0KX': 'Lieutenant – Customs',
  '0KY': 'Master – Secondary Education',
  '0KZ': 'Second Lieutenant – Customs',
  // ── 0L1 – 0LZ ────────────────────────────────────────────────────────────
  '0L1': 'Master – Technical Education',
  '0L2': 'Principal Physician – Hospitals',
  '0L3': 'Hospital Physician',
  '0L4': 'Warrant Officer Major – Customs',
  '0L5': 'Chief Warrant Officer Sc. 3 – Customs',
  '0L6': 'Chief Warrant Officer Sc. 2 – Customs',
  '0L7': 'Principal Master 2nd Category',
  '0L8': 'Chief Warrant Officer Sc. 1 – Customs',
  '0L9': 'Warrant Officer Sc. 1 – Customs',
  '0LA': 'Principal Master 1st Category',
  '0LB': 'Warrant Officer Sc. 2 – Customs',
  '0LC': 'Warrant Officer Sc. 3 – Customs',
  '0LD': 'Archaeological Research Master',
  '0LE': 'Sergeant Major Sc. 3 – Customs',
  '0LF': 'Sergeant Major Sc. 2 – Customs',
  '0LG': 'Communications Reception Agent',
  '0LH': 'Sergeant Major Sc. 1 – Customs',
  '0LI': 'Sergeant Sc. 3 – Customs',
  '0LJ': 'Customs Sailor',
  '0LK': 'Sergeant Sc. 2 – Customs',
  '0LL': 'Administrator General – Court Registry',
  '0LM': 'Data Entry Operator',
  '0LN': 'Major Nurse – PH',
  '0LP': 'Principal Physician – PH',
  '0LQ': 'Sergeant Sc. 1 – Customs',
  '0LR': 'Temporary Physician – PH',
  '0LS': 'Public Health Physician',
  '0LT': 'Cooperative Contract Physician',
  '0LU': 'Cooperative Contract Physician – International Law',
  '0LV': 'Principal Specialist Vet. Sanitarian',
  '0LW': 'Principal Specialist Physician – PH',
  '0LX': 'Corporal Chief – Customs',
  '0LY': 'Specialist Physician – PH',
  '0LZ': 'Temporary Specialist Physician – PH',
  // ── 0M1 – 0MZ ────────────────────────────────────────────────────────────
  '0M1': 'Sanitary Veterinarian',
  '0M2': 'Temporary Veterinarian',
  '0M3': 'Temporary Part-time Veterinarian',
  '0M4': 'General Inspector – Veterinary Medicine',
  '0M5': 'Divisional Inspector – Veterinary Medicine',
  '0M6': 'Regional Inspector – Veterinary Medicine',
  '0M7': 'Chief Veterinarian',
  '0M8': 'Customs Corporal',
  '0M9': 'Principal Veterinarian',
  '0MA': 'Chief Laboratory Veterinarian',
  '0MB': 'Specialist Veterinarian',
  '0MC': 'Temporary Specialist Veterinarian',
  '0MD': 'Sound Director',
  '0ME': 'Deputy Corporal – Customs',
  '0MF': 'Deputy Counselor – Administrative Tribunal',
  '0MG': 'Minister Plenipotentiary',
  '0MH': 'Administrator General – Court of Accounts Registry',
  '0MI': 'Chief Administrator – Court of Accounts Registry',
  '0MJ': 'Minister Plenipotentiary (Honorary Class)',
  '0MK': 'General Conservator – Heritage',
  '0ML': 'Chief Conservator – Heritage',
  '0MM': 'Teacher (fem.) / Moallimat',
  '0MN': 'Senior Conservator – Heritage',
  '0MP': 'Monitor',
  '0MQ': 'Heritage Conservator',
  '0MR': 'Deputy Conservator – Heritage',
  '0MS': 'Chief Manager – Outreach & Education Programs',
  '0MT': 'Assistant Conservator – Heritage',
  '0MU': 'Heritage Supervisor',
  '0MV': 'Monitor – Arts Education',
  '0MW': 'Heritage Agent',
  '0MX': 'Principal Agrégé Professor',
  '0MY': 'Corporal Major – Presidential Guard',
  '0MZ': 'Deputy Manager – OEP',
  // ── 0N0 – 0NZ ────────────────────────────────────────────────────────────
  '0N0': 'Deputy Technical Police Officer',
  '0N1': 'Film Editor',
  '0N2': 'Principal Police Officer',
  '0N3': 'Deputy Police Officer',
  '0N4': 'Musician 2nd Category',
  '0N5': 'Chief Police Inspector',
  '0N6': 'Principal Police Inspector',
  '0N7': 'Musician 1st Category',
  '0N8': 'Counselor – PTT (Post & Telecom)',
  '0N9': 'Agrégé Professor',
  '0NA': 'General Analyst',
  '0NB': 'Chief Analyst',
  '0NC': 'Central Analyst',
  '0ND': 'Trainee Musician 1st Category',
  '0NE': 'Trainee Musician 2nd Category',
  '0NF': 'IT Laboratory Technician',
  '0NG': 'Deputy Officer – Navy',
  '0NH': 'Chief Technician',
  '0NI': 'Principal Technician',
  '0NJ': 'Divisional Naval Officer',
  '0NK': 'Technician',
  '0NL': 'Inspector – 1st Degree, Youth and Childhood',
  '0NM': 'Navy Marine Officer',
  '0NN': 'Technical Police Officer',
  '0NP': 'Peace Officer',
  '0NQ': 'General Inspector – Education',
  '0NR': 'Animator – Senior Category',
  '0NS': 'Principal Peace Officer',
  '0NT': 'Principal Inspector – School Life',
  '0NU': 'Principal Inspector – Physical Education & School Life',
  '0NV': 'Police Officer',
  '0NW': 'Principal Inspector – Primary Economy',
  '0NX': 'Inspector – Preparatory School & School Life',
  '0NY': 'Technical Police Officer',
  '0NZ': 'Inspector – Primary Schools',
  // ── 0P1 – 0PZ ────────────────────────────────────────────────────────────
  '0P1': 'Senior Officer 2nd Class – Navy',
  '0P2': 'Colonel – Presidency of the Republic',
  '0P3': 'Professor (Higher Class) – Physical & Sports Activities',
  '0P4': 'Senior Officer 1st Class – Navy',
  '0P5': 'Senior Officer 3rd Class – Navy',
  '0P6': 'Lieutenant Colonel – Presidential Guard',
  '0P7': 'Animator 1st Category',
  '0P8': 'Commander – Presidential Guard',
  '0P9': 'Captain – Presidential Guard',
  '0PA': 'Animator 2nd Category',
  '0PB': 'Corporal Chief – Presidential Guard',
  '0PC': 'Corporal – Presidential Guard',
  '0PD': 'Operator',
  '0PE': 'General Documentation Manager',
  '0PF': 'Chief Doc./Archive Manager',
  '0PG': 'Chief Operator',
  '0PH': 'Counselor Doc./Archive Manager',
  '0PI': 'Documentation / Archive Manager',
  '0PJ': 'Camera Operator',
  '0PK': 'Deputy Doc./Archive Manager',
  '0PL': 'Professor (Higher Class) – Education',
  '0PM': 'Worker Category 1',
  '0PN': 'Professor (Higher Class) – Education',
  '0PP': 'Worker Category 2',
  '0PQ': 'Principal Professor (Higher Class)',
  '0PR': 'Principal Professor',
  '0PS': 'Worker Category 3',
  '0PT': 'Professor / Teacher',
  '0PU': 'Professor (Higher Class) – Laboratory',
  '0PV': 'Worker Category 4',
  '0PW': 'Primary School Teacher',
  '0PX': 'Principal Professor (Higher Class) – Physical Education',
  '0PY': 'Worker Category 5',
  '0PZ': 'Professor (Higher Class) – Physical Education',
  // ── 0Q1 – 0QZ ────────────────────────────────────────────────────────────
  '0Q1': 'Worker Category 6',
  '0Q2': 'Captain – Penitentiary Services',
  '0Q3': 'Lieutenant – Penitentiary Services',
  '0Q4': 'Worker Category 7',
  '0Q5': 'Second Lieutenant – Penitentiary Services',
  '0Q6': 'Group Animator – Penitentiary Services',
  '0Q7': 'Worker Category 8',
  '0Q8': 'Re-education Instructor',
  '0Q9': 'Occasional Worker',
  '0QA': 'Worker Category 9',
  '0QB': 'Temporary Corporal Chief – Prisons',
  '0QC': 'Prison Corporal',
  '0QD': 'Worker Category 10',
  '0QE': 'Major Vet. Sanitarian',
  '0QF': 'Principal Professor – Physical & Sports Activities',
  '0QG': 'Customs Patron',
  '0QH': 'Professor – Physical & Sports Activities',
  '0QI': 'Principal Education Counselor',
  '0QJ': 'Education Counselor',
  '0QK': 'Physical & Sports Activities Educator',
  '0QL': 'Deputy Education Counselor',
  '0QM': 'Specialist Pharmacist – PH',
  '0QN': 'Principal Specialist Pharmacist',
  '0QP': 'Temporary Pharmacist – PH',
  '0QQ': 'Temporary Biologist Pharmacist – PH',
  '0QR': 'Major Pharmacist – PH',
  '0QS': 'Major Specialist Pharmacist',
  '0QT': 'Principal Counselor Supervisor',
  '0QU': 'Counselor Supervisor',
  '0QV': 'Principal Pharmacist – PH',
  '0QW': 'Physical & Sports Educator',
  '0QX': 'General Inspector – Youth and Childhood',
  '0QY': 'Public Health Pharmacist',
  '0QZ': 'Principal Inspector – Youth and Childhood',
  // ── 0R1 – 0RZ ────────────────────────────────────────────────────────────
  '0R1': 'Pilot Category A',
  '0R2': 'Colonel – Security',
  '0R3': 'Corporal Chief – Security',
  '0R4': 'Pilot Category B',
  '0R5': 'Lieutenant – Presidential Guard',
  '0R6': 'Second Lieutenant – Presidential Guard',
  '0R7': 'Pilot Category C',
  '0R8': 'Chief Warrant Officer – Presidential Guard',
  '0R9': 'Warrant Officer – Presidential Guard',
  '0RA': 'Pilot Category D',
  '0RB': 'Pilot Category E',
  '0RC': 'Pilot Category F',
  '0RD': 'Sergeant Chief – Presidential Guard',
  '0RE': 'Application Initiator',
  '0RF': 'Initiator',
  '0RG': 'Preacher',
  '0RH': 'Principal Preacher (Higher Class)',
  '0RI': 'Principal Application Initiator',
  '0RJ': 'First Assistant Director',
  '0RK': 'Sergeant – Presidential Guard',
  '0RL': 'Principal Professor – Youth and Childhood',
  '0RM': 'Professor (Higher Class) – Youth and Childhood',
  '0RN': 'Master Apprentice – Cat. A2',
  '0RP': 'First Petty Officer – Customs',
  '0RQ': 'Principal Counselor – Prisons',
  '0RS': 'First Secretary – Film Production',
  '0RT': 'Professor (Higher Class) – Youth and Childhood',
  '0RU': 'Professor – Youth and Childhood',
  '0RV': 'Preparer 1st Category',
  '0RW': 'Counselor – Prisons',
  '0RX': 'Certificated Student Sailor',
  '0RY': 'Preparer 2nd Category',
  '0RZ': 'Commander – Magistrate 3rd Grade',
  // ── 0S1 – 0SZ ────────────────────────────────────────────────────────────
  '0S1': 'Reception Agent – Financial Services',
  '0S2': 'Controller General – Public Services',
  '0S3': 'Deputy Controller – Public Services',
  '0S4': 'Reception Agent – Library',
  '0S5': 'Reception Agent – Documentation',
  '0S6': 'Reception Agent – Archives',
  '0S7': 'Presenter / Animator',
  '0S8': 'Controller – Public Services',
  '0S9': 'Principal Educator – Physical & Sports Activities',
  '0SA': 'Administrator General – OEP',
  '0SB': 'Chief Administrator – OEP',
  '0SC': 'Senior Administrator – OEP',
  '0SD': 'Principal Supervisor',
  '0SE': 'Sub-Brigadier of the Peace',
  '0SF': 'Guardian of the Peace (Police)',
  '0SG': 'Agrégé Professor – Secondary Education',
  '0SH': 'Corporal Chief – Peace',
  '0SI': 'Corporal of the Peace',
  '0SJ': 'Counselor Doc./Archive Manager – OEP',
  '0SK': 'Physical Education Teacher',
  '0SL': 'Prof. – Physical Education, 1st Cycle',
  '0SM': 'Professor – Secondary Arts Education',
  '0SN': 'Professor – Paramedical Education, 1st Cycle',
  '0SP': 'Professor – Arts Education, 1st Cycle',
  '0SQ': 'Principal Educator – Sports',
  '0SR': 'Chief Controller – Public Services',
  '0SS': 'Professor – Secondary Education',
  '0ST': 'Principal Professor – Arts Education',
  '0SU': 'Peace Agent (Police)',
  '0SV': 'Professor – Secondary Education, 1st Cycle',
  '0SW': 'University Hospital Professor – Pharmacy',
  '0SX': 'Agrégé Master of Conferences – Pharmacy',
  '0SY': 'Professor – Technical Education',
  '0SZ': 'Principal Professor – Technical Education',
  // ── 0T0 – 0TZ ────────────────────────────────────────────────────────────
  '0T0': 'Warrant Officer Major Sc. 4',
  '0T1': 'Professor – Higher Education',
  '0T2': 'Principal Professor – Secondary Education',
  '0T3': 'Master Apprentice – Social Education',
  '0T4': 'Professor – Higher Agricultural Education',
  '0T5': 'Professor – Paramedical Education',
  '0T6': 'University Hospital Professor – Dental Medicine',
  '0T7': 'Professor – Technical Education, 1st Cycle',
  '0T8': 'University Hospital Professor – Pharmacy',
  '0T9': 'University Hospital Professor – Medicine',
  '0TA': 'Programmer',
  '0TB': 'University Hospital Professor – Veterinary Medicine',
  '0TC': 'Colonel – National Security',
  '0TD': 'Lieutenant Colonel – National Security',
  '0TE': 'Commander – National Security',
  '0TF': 'Captain – National Security',
  '0TG': 'TV Director Cat. A',
  '0TH': 'TV Director Cat. B',
  '0TI': 'Lieutenant – National Security',
  '0TJ': 'Deputy Editor – Debates',
  '0TK': 'General Manager – OEP',
  '0TL': 'Colonel Major – Presidential Guard',
  '0TM': 'Medical Resident',
  '0TN': 'Dental Medicine Resident',
  '0TP': 'Veterinary Medicine Resident',
  '0TQ': 'Biology Resident',
  '0TR': 'Second Lieutenant – National Security',
  '0TS': 'Deputy Secretary – FA',
  '0TT': 'Chief Warrant Officer Sc. 4',
  '0TU': 'Director Secretary',
  '0TV': 'Administrative Secretary',
  '0TW': 'Brigadier Chief of the Peace',
  '0TX': 'Brigadier of the Peace',
  '0TY': 'Secretary – Foreign Affairs',
  '0TZ': 'Assistant – University Hospital Pharmacy',
  // ── 0U1 – 0UZ ────────────────────────────────────────────────────────────
  '0U1': 'Cipher Secretary – FA',
  '0U2': 'Chief Secretary-Registrar',
  '0U3': 'Principal Secretary-Registrar',
  '0U4': 'Cultural Secretary',
  '0U5': 'Secretary-Registrar',
  '0U6': 'Orthopaedic Applications Engineer',
  '0U7': 'Deputy Cultural Secretary',
  '0U8': 'Deputy Orthopaedic Applications Engineer',
  '0U9': 'Orthopaedic Applications Technical Assistant',
  '0UA': 'Principal Cultural Secretary',
  '0UB': 'Doc./Archive Manager – OEP',
  '0UC': 'Temporary Corporal Chief – National Guard',
  '0UD': 'Police Secretary',
  '0UE': 'Temporary Corporal – National Guard',
  '0UF': 'Temporary Guard – National Guard',
  '0UG': 'Press Secretary',
  '0UH': 'Corporal Major – National Guard',
  '0UJ': 'Deputy Press Secretary',
  '0UK': 'Principal Press Secretary',
  '0UL': 'Secretary-Stenographer',
  '0UM': 'Pedagogical Inspector – Vocational Training',
  '0UN': 'Sergeant Scale 1',
  '0UP': 'Sergeant Scale 2',
  '0UQ': 'Sergeant Major Scale III',
  '0UR': 'Sergeant Scale 3',
  '0US': 'Sergeant Major Scale I',
  '0UT': 'Sergeant Chief Scale 1',
  '0UU': 'Sergeant Chief Scale 2',
  '0UV': 'Sergeant Chief Scale 1',
  '0UW': 'Sergeant Chief – National Guard',
  '0UX': 'Sergeant Chief – Civil Protection',
  '0UY': 'Sergeant – National Guard',
  '0UZ': 'Sergeant – Civil Protection',
  // ── 0V1 – 0VZ ────────────────────────────────────────────────────────────
  '0V1': 'Student NCO 1st Year',
  '0V2': 'Sub-Brigadier – Presidential Guard',
  '0V3': 'Second Lieutenant (ADL)',
  '0V4': 'Second Lieutenant – National Guard',
  '0V5': 'Second Lieutenant (PDL)',
  '0V6': 'Second Lieutenant – Civil Protection',
  '0V7': 'Speaker / Announcer',
  '0V8': 'Medical Intern',
  '0V9': 'Internal Trainee',
  '0VA': 'Research Trainee',
  '0VB': 'Dental Medicine Intern',
  '0VC': 'Student NCO 2nd Year',
  '0VD': 'Student NCO 3rd Year',
  '0VE': 'Active Corporal Student',
  '0VF': 'General Engineer – Agricultural Training',
  '0VG': 'Supervisor 1st Category',
  '0VH': 'Agricultural and Fishing Trainer',
  '0VI': 'Chief Engineer – Agricultural Training',
  '0VJ': 'Supervisor 2nd Category',
  '0VK': 'Principal Engineer – Agricultural Training',
  '0VL': 'Agricultural Trainer',
  '0VM': 'Supervisor 3rd Category',
  '0VN': 'Chief Agricultural and Fishing Trainer',
  '0VO': 'Deputy Warrant Officer Major Sc. 4',
  '0VP': 'Chief Warrant Officer – Prisons',
  '0VQ': 'Principal Petty Officer Scale 4',
  '0VR': 'Principal Agricultural and Fishing Trainer',
  '0VS': 'Corporal Major – Prisons',
  '0VT': 'Captain – Magistrate 1st Grade',
  '0VU': 'Lieutenant – Magistrate 1st Grade',
  '0VV': 'General Supervisor 1st Category',
  '0VW': 'Second Lieutenant – Magistrate 1st Grade',
  '0VX': 'Education Counselor – Agriculture',
  '0VY': 'General Supervisor 2nd Category',
  '0VZ': 'Senior Animator',
  // ── 0W1 – 0WZ ────────────────────────────────────────────────────────────
  '0W1': 'General Psychologist',
  '0W2': 'Chief Psychologist',
  '0W3': 'Principal Psychologist',
  '0W4': 'Psychologist',
  '0W5': 'Application Animator',
  '0W6': 'Principal Animator',
  '0W7': 'Principal Inspector – Special Education',
  '0W8': 'Special Education Inspector',
  '0W9': 'Special Educator',
  '0WA': 'Multidisciplinary Educator',
  '0WB': 'Special Education Auxiliary',
  '0WD': 'General Editor – Civil Service Council',
  '0WE': 'Chief Editor – Civil Service Council',
  '0WF': 'Principal Editor – Civil Service Council',
  '0WG': 'Editor – Civil Service Council',
  '0WH': 'Deputy Editor – Civil Service Council',
  '0WI': 'General Corps – Magistrate 2nd Grade',
  '0WJ': 'General Corps – Magistrate 3rd Grade',
  '0WK': 'Major General – Magistrate 2nd Grade',
  '0WL': 'Major General – Magistrate 3rd Grade',
  '0WM': 'Brigadier General – Magistrate 2nd Grade',
  '0WN': 'Brigadier General – Magistrate 3rd Grade',
  '0WP': 'Colonel Major – Magistrate 1st Grade',
  '0WQ': 'Colonel Major – Magistrate 2nd Grade',
  '0WR': 'Colonel Major – Magistrate 3rd Grade',
  '0WS': 'Colonel – Magistrate 1st Grade',
  '0WT': 'Colonel – Magistrate 2nd Grade',
  '0WU': 'Colonel – Magistrate 3rd Grade',
  '0WV': 'Lieutenant Colonel – Magistrate 1st Grade',
  '0WW': 'Lieutenant Colonel – Magistrate 2nd Grade',
  '0WX': 'Lieutenant Colonel – Magistrate 3rd Grade',
  '0WY': 'Commander – Magistrate 1st Grade',
  '0WZ': 'Commander – Magistrate 2nd Grade',
  // ── 0X0 – 0XZ ────────────────────────────────────────────────────────────
  '0X0': 'Lieutenant Colonel – Veterinary Medicine',
  '0X1': 'Colonel Major – Dental Surgeon',
  '0X2': 'Colonel – Physician',
  '0X3': 'Colonel – Veterinary Surgeon',
  '0X4': 'Colonel – Pharmacist',
  '0X5': 'Colonel – Dental Surgeon',
  '0X6': 'Lieutenant Colonel – Physician',
  '0X7': 'Sergeant Chief – Penitentiary Services',
  '0X8': 'Lieutenant Colonel – Pharmacist',
  '0X9': 'Lieutenant Colonel – Dental Surgeon',
  '0XA': 'Colonel Major – Prisons',
  '0XB': 'Warrant Officer – Penitentiary Services',
  '0XC': 'Commander – Physician',
  '0XD': 'Sergeant – Penitentiary Services',
  '0XE': 'Commander – Veterinary Surgeon',
  '0XF': 'Commander – Pharmacist',
  '0XG': 'Laboratory Technician',
  '0XH': 'Commander – Dental Surgeon',
  '0XI': 'Captain – Physician',
  '0XJ': 'Captain – Veterinary Surgeon',
  '0XK': 'Captain – Pharmacist',
  '0XL': 'Captain – Dental Surgeon',
  '0XM': 'Superior Technician – PH',
  '0XN': 'Lieutenant – Physician',
  '0XP': 'Lieutenant – Veterinary Surgeon',
  '0XQ': 'Lieutenant – Pharmacist',
  '0XR': 'Lieutenant – Dental Surgeon',
  '0XS': 'Professor – Military Higher Education',
  '0XT': 'Master of Conferences – Military Higher Education',
  '0XU': 'Urban Planner',
  '0XV': 'Chief Urban Planner',
  '0XW': 'Divisional Urban Planner',
  '0XX': 'Urban Planner General',
  '0XY': 'Principal Urban Planner',
  '0XZ': 'Master Assistant – Military Higher Education',
  // ── 0Y1 – 0YZ ────────────────────────────────────────────────────────────
  '0Y1': 'Temporary Agent Cat. A1',
  '0Y2': 'Major Superior Technician – PH',
  '0Y3': 'Temporary Agent Cat. A2',
  '0Y4': 'Principal Superior Technician – PH',
  '0Y5': 'Temporary Agent Cat. A3',
  '0Y6': 'Deputy Education Counselor – Agriculture',
  '0Y7': 'Temporary Agent Cat. B',
  '0Y8': 'Principal Counselor Supervisor',
  '0Y9': 'Temporary Agent Cat. C',
  '0YA': 'General Corps – Veterinary Medicine',
  '0YB': 'Temporary Agent Cat. D',
  '0YC': 'Brigadier General – Physician',
  '0YD': 'Brigadier General – Veterinary Surgeon',
  '0YE': 'Brigadier General – Pharmacist',
  '0YF': 'Brigadier General – Dental Surgeon',
  '0YG': 'General Corps – Physician',
  '0YH': 'Active National Service Volunteer',
  '0YI': 'Administrator – Chamber of Deputies',
  '0YJ': 'Clerk – Chamber of Deputies',
  '0YK': 'Secretary – Chamber of Deputies',
  '0YL': 'Counselor 1st Order',
  '0YM': 'Counselor 2nd Order',
  '0YN': 'Counselor 3rd Order',
  '0YP': 'Deputy Administrator – Chamber of Deputies',
  '0YQ': 'Reception Agent – Chamber of Deputies',
  '0YR': 'General Corps – Pharmacist',
  '0YS': 'General Corps – Dental Surgeon',
  '0YT': 'Major General – Physician',
  '0YU': 'Major General – Veterinary Surgeon',
  '0YV': 'Major General – Pharmacist',
  '0YW': 'Major General – Dental Surgeon',
  '0YX': 'Colonel Major – Physician',
  '0YY': 'Colonel Major – Veterinary Surgeon',
  '0YZ': 'Colonel Major – Pharmacist',
  // ── 0Z1 – 0ZZ ────────────────────────────────────────────────────────────
  '0Z1': 'Tunisian Contract Employee',
  '0Z2': 'UN Expert Cat. 1',
  '0Z3': 'UN Expert Cat. 2',
  '0Z4': 'UN Expert Cat. 3',
  '0Z5': 'UN Expert Cat. 4',
  '0Z6': 'Teaching Student',
  '0Z7': 'Teaching Instructor',
  '0Z8': 'Technical Contract Master',
  '0Z9': 'Contract Research Student',
  '0ZA': 'Contract Artisan',
  '0ZB': 'Special Contract Employee',
  '0ZC': 'Contract Trainer',
  '0ZD': 'Foreign Contract Employee',
  '0ZE': 'New Technology Technical Expert 1',
  '0ZF': 'New Technology Technical Expert 2',
  '0ZG': 'New Technology Technical Expert',
  '0ZH': 'Contract Training Counselor',
  '0ZI': 'Contract Employee (1,250 TND)',
  '0ZJ': 'Retired Expert Contract 1',
  '0ZK': 'Retired Expert Contract 2',
  '0ZL': 'Administrator General – Registry',
  '0ZM': 'Chief Administrator – Registry',
  '0ZN': 'Senior Administrator – Registry',
  '0ZP': 'Registry Administrator',
  '0ZQ': 'Principal Registrar',
  '0ZR': 'Registrar',
  '0ZS': 'Deputy Registrar',
  '0ZT': 'Tribunal Bailiff',
  '0ZU': 'Half-time Contract Assistant',
  '0ZV': 'General Sports Manager',
  '0ZW': 'Chief Sports Manager',
  '0ZX': 'Unidentified Grade',
  '0ZY': 'Senior Sports Manager',
  '0ZZ': 'Sports Manager',
  // ── 100 – 105 (Elected officials) ────────────────────────────────────────
  '100': 'Deputy (Member of Parliament)',
  '101': 'Vice President – Assembly of People\'s Representatives',
  '102': 'President – Assembly of People\'s Representatives',
  '103': 'Deputy – National Council of Regions & Districts',
  '104': 'President – National Council',
  '105': 'Vice President – National Council',
  // ── 13x (Healthcare support) ──────────────────────────────────────────────
  '13A': 'Principal Home Care Aide – PH',
  '13B': 'Major Home Care Aide – PH',
  '13C': 'Major Part-time Home Care Aide – PH',
  '13D': 'Principal Application Agent',
  '13E': 'Application Agent – PH',
  '13F': 'Cooperative Assistant',
  '13G': 'Deputy Application Agent',
  '13H': 'Enhanced Application Agent – PH',
  // ── 140 ──────────────────────────────────────────────────────────────────
  '140': 'Head of State',
  // ── 1Ax / 1Bx (Military/Security variants) ───────────────────────────────
  '1A0': 'Lieutenant – National Guard',
  '1A1': 'Warrant Officer – National Guard',
  '1A2': 'Sergeant – National Guard',
  '1A3': 'Corporal – National Guard',
  '1A4': 'Warrant Officer – National Guard',
  '1A5': 'Sergeant – National Guard',
  '1A6': 'Corporal – National Guard',
  '1A7': 'Lieutenant – National Guard',
  '1A8': 'Lieutenant – National Security',
  '1A9': 'Guardian of the Peace',
  '1B0': 'Brigadier of the Peace',
  '1B1': 'Corporal – National Security',
  // ── 1Ex (University Hospital – Medical Academic) ─────────────────────────
  '1EA': 'Commander – University Hospital Medicine (MCA)',
  '1EB': 'Lieutenant Colonel – University Hospital Medicine (MCA)',
  '1EC': 'Major General – University Hospital Medicine (MCA)',
  '1ED': 'General Corps – University Hospital Medicine (MCA)',
  '1EE': 'Colonel Major – University Hospital Medicine (MCA)',
  '1EF': 'Colonel – University Hospital Medicine (MCA)',
  '1EG': 'Brigadier General – University Hospital Medicine (MCA)',
  '1EH': 'Captain – University Hospital Medicine (MCA)',
  '1EI': 'Commander – University Hospital Vet. Med. (MCA)',
  '1EJ': 'Lieutenant Colonel – University Hospital Vet. Med. (MCA)',
  '1EK': 'Major General – University Hospital Vet. Med. (MCA)',
  '1EL': 'General Corps – University Hospital Vet. Med. (MCA)',
  '1EM': 'Colonel Major – University Hospital Vet. Med. (MCA)',
  '1EN': 'Colonel – University Hospital Vet. Med. (MCA)',
  '1EO': 'Brigadier General – University Hospital Vet. Med. (MCA)',
  '1EP': 'Captain – University Hospital Vet. Med. (MCA)',
  '1JP': 'Cooperative Master Assistant',
  '1KD': 'Cooperative Master of Conferences',
  // ── 1Px (Police – duplicate codes) ───────────────────────────────────────
  '1P0': 'Police Commissioner General 1st Class',
  '1P1': 'Police Commissioner General 2nd Class',
  '1P2': 'Senior Class Police Commissioner',
  '1P3': 'Principal Police Commissioner',
  '1P4': 'Police Commissioner',
  '1P5': 'Principal Police Officer',
  '1P6': 'Police Officer',
  '1P7': 'Deputy Police Officer',
  '1P8': 'Principal Police Inspector',
  '1P9': 'Police Inspector',
  // ── 1Tx (Security / Prison variants) ─────────────────────────────────────
  '1T0': 'Chief Prison Guard',
  '1T1': 'Cooperative Higher Education Professor',
  '1T2': 'Corporal – National Security',
  '1T3': 'Corporal Major – National Security',
  '1T4': 'Corporal Chief – National Guard',
  '1T5': 'Corporal – National Guard',
  '1T6': 'Temporary Corporal Chief – National Security',
  '1T7': 'Colonel Major – National Security',
  '1T8': 'Temporary Agent – National Guard',
  '1T9': 'Prison Guard',
  '1TA': 'Deputy Chief Prison Guard',
  '1TR': 'General – National Guard',
  '1TS': 'General – Civil Protection',
  // ── 1Yx (Medical – Military) ──────────────────────────────────────────────
  '1Y0': 'Captain – Physician (Cooperative)',
  '1Y1': 'Brigadier General – Dental Surgeon',
  '1Y2': 'Commander – Dental Surgeon',
  '1Y3': 'Major General – Dental Surgeon',
  '1Y4': 'General Corps – Dental Surgeon',
  '1Y5': 'Colonel Major – Dental Surgeon',
  '1Y6': 'Lieutenant – Dental Surgeon',
  '1Y7': 'Lieutenant Colonel – Dental Surgeon',
  '1Y8': 'Colonel – Dental Surgeon',
  '1Y9': 'Captain – Dental Surgeon',
  '1YA': 'Brigadier General – Physician',
  '1YB': 'Commander – Physician',
  '1YC': 'Major General – Physician',
  '1YD': 'General Corps – Physician',
  '1YE': 'Colonel Major – Physician',
  '1YG': 'Lieutenant Colonel – Physician',
  '1YH': 'Colonel – Physician',
  '1YI': 'Captain – Physician',
  '1YJ': 'Brigadier General – Physician (PH)',
  '1YK': 'Commander – Physician (PH)',
  '1YL': 'Major General – Physician',
  '1YM': 'General Corps – Physician (PH)',
  '1YN': 'Colonel Major – Physician (PH)',
  '1YP': 'Lieutenant Colonel – Physician (PH)',
  '1YQ': 'Colonel – Physician (PH)',
  '1YR': 'Captain – Physician (PH)',
  '1YS': 'Brigadier General – Physician (Cooperative)',
  '1YT': 'Commander – Physician (Cooperative)',
  '1YU': 'Major General – Physician (Cooperative)',
  '1YV': 'General Corps – Physician (Cooperative)',
  '1YW': 'Colonel Major – Physician (Cooperative)',
  '1YY': 'Lieutenant Colonel – Physician (Cooperative)',
  '1YZ': 'Colonel – Physician (Cooperative)',
  // ── 2Yx (Medical – Pharmacist/Dental) ─────────────────────────────────────
  '2Y0': 'Captain – Pharmacist',
  '2Y1': 'Brigadier General – Dental Surgeon',
  '2Y2': 'Commander – Dental Surgeon',
  '2Y3': 'Major General – Dental Surgeon',
  '2Y4': 'General Corps – Dental Surgeon',
  '2Y5': 'Colonel Major – Dental Surgeon',
  '2Y6': 'Lieutenant – Dental Surgeon',
  '2Y7': 'Lieutenant Colonel – Dental Surgeon',
  '2Y8': 'Colonel – Dental Surgeon',
  '2Y9': 'Captain – Dental Surgeon',
  '2YA': 'Brigadier General – Dental Surgeon',
  '2YB': 'Commander – Dental Surgeon',
  '2YC': 'Major General – Dental Surgeon',
  '2YD': 'General Corps – Dental Surgeon',
  '2YE': 'Colonel Major – Dental Surgeon',
  '2YF': 'Lieutenant – Dental Surgeon',
  '2YG': 'Lieutenant Colonel – Dental Surgeon',
  '2YH': 'Colonel – Dental Surgeon',
  '2YI': 'Captain – Dental Surgeon',
  '2YJ': 'Brigadier General – Pharmacist',
  '2YK': 'Commander – Pharmacist',
  '2YL': 'Major General – Pharmacist',
  '2YM': 'General Corps – Pharmacist',
  '2YN': 'Colonel Major – Pharmacist',
  '2YO': 'Lieutenant – Pharmacist',
  '2YP': 'Lieutenant Colonel – Pharmacist',
  '2YQ': 'Colonel – Pharmacist (PH)',
  '2YR': 'Captain – Pharmacist',
  '2YS': 'Brigadier General – Pharmacist',
  '2YT': 'Commander – Pharmacist',
  '2YU': 'Major General – Pharmacist',
  '2YV': 'General Corps – Pharmacist',
  '2YW': 'Colonel Major – Pharmacist',
  '2YX': 'Lieutenant – Pharmacist',
  '2YY': 'Lieutenant Colonel – Pharmacist',
  '2YZ': 'Colonel – Pharmacist (PH)',
  // ── 3Yx (Medical – Pharmacist/Vet) ────────────────────────────────────────
  '3Y0': 'Brigadier General – Pharmacist',
  '3Y1': 'Commander – Pharmacist',
  '3Y2': 'Major General – Pharmacist',
  '3Y3': 'General Corps – Pharmacist',
  '3Y4': 'Colonel Major – Pharmacist',
  '3Y5': 'Lieutenant – Pharmacist',
  '3Y6': 'Lieutenant Colonel – Pharmacist',
  '3Y7': 'Colonel – Pharmacist (PH)',
  '3Y8': 'Captain – Pharmacist',
  '3Y9': 'Brigadier General – Vet. Surgeon',
  '3YA': 'Commander – Vet. Surgeon',
  '3YB': 'Major General – Vet. Surgeon',
  '3YC': 'General Corps – Vet. Surgeon',
  '3YD': 'Colonel Major – Vet. Surgeon',
  '3YE': 'Lieutenant – Vet. Surgeon',
  '3YF': 'Lieutenant Colonel – Vet. Surgeon',
  '3YG': 'Colonel – Vet. Surgeon',
  '3YH': 'Captain – Vet. Surgeon',
  '3YI': 'Brigadier General – Vet. Surgeon',
  '3YJ': 'Commander – Vet. Surgeon',
  '3YK': 'Major General – Vet. Surgeon',
  '3YL': 'General Corps – Vet. Surgeon',
  '3YM': 'Colonel Major – Vet. Surgeon',
  '3YN': 'Lieutenant – Vet. Surgeon',
  '3YO': 'Lieutenant Colonel – Vet. Surgeon',
  '3YP': 'Colonel – Vet. Surgeon',
  '3YQ': 'Captain – Vet. Surgeon',
  '3YR': 'Brigadier General – Vet. Surgeon',
  '3YS': 'Commander – Vet. Surgeon',
  '3YT': 'Major General – Vet. Surgeon',
  '3YU': 'General Corps – Vet. Surgeon',
  '3YV': 'Colonel Major – Vet. Surgeon',
  '3YW': 'Lieutenant – Vet. Surgeon',
  '3YX': 'Lieutenant Colonel – Vet. Surgeon',
  '3YY': 'Colonel – Vet. Surgeon',
  '3YZ': 'Captain – Vet. Surgeon',
  // ── 5Ax (Local / Regional Council members) ───────────────────────────────
  '5A0': 'Local Council Member',
  '5A1': 'Local Council Member (elected)',
  '5A2': 'Regional Council Member',
  '5A3': 'Regional Council Member (elected)',
  '5A4': 'District Council Member',
  '5A5': 'District Council Member (elected)',
  // ── 999 ──────────────────────────────────────────────────────────────────
  '999': 'Unidentified Grade',
  // ── A-series (duplicate/parallel civil service grades) ────────────────────
  A01: 'Administrator General',
  A02: 'Chief Administrator',
  A03: 'Senior Administrator',
  A04: 'Administrator',
  A05: 'Administrative Attaché',
  A06: 'Administrative Secretary',
  A07: 'Stenographer Secretary',
  A08: 'Administrative Clerk',
  A09: 'Typist',
  A10: 'Reception Agent',
  A11: 'Deputy Typist',
  A21: 'Worker Category 1',
  A22: 'Worker Category 2',
  A23: 'Worker Category 3',
  A24: 'Worker Category 4',
  A25: 'Worker Category 5',
  A26: 'Worker Category 6',
  A27: 'Worker Category 7',
  A28: 'Worker Category 8',
  A29: 'Worker Category 9',
  A30: 'Worker Category 10',
  A31: 'Chief Technician',
  A32: 'Principal Technician',
  A33: 'Technician',
  A34: 'Technical Assistant',
  A35: 'Technical Agent',
  A41: 'Engineer General',
  A42: 'Chief Engineer',
  A43: 'Principal Engineer',
  A44: 'Works Engineer',
  A51: 'Architect General',
  A52: 'Chief Architect',
  A53: 'Principal Architect',
  A54: 'Divisional Architect',
  A55: 'Architect',
  A61: 'General Analyst',
  A62: 'Chief Analyst',
  A63: 'Central Analyst',
  A64: 'Principal Analyst',
  A65: 'Analyst',
  A66: 'Programmer',
  A67: 'IT Laboratory Technician',
  A68: 'Kindergarten Application Animator',
  A69: 'Kindergarten Application Animator',
  A70: 'Kindergarten Senior Animator',
  A71: 'Principal Kindergarten Animator',
  A72: 'Kindergarten Application Animator',
  A73: 'Kindergarten Application Animator',
  // ── AH series (Sports / Physical Education) ───────────────────────────────
  AH1: 'Professor – 1st Class, Sports',
  AH2: 'Professor – Higher Class, Sports',
  AH3: 'Emeritus Professor – Sports',
  AH4: 'Expert Emeritus Professor – Sports',
  AH5: 'Principal Emeritus Professor – Sports',
  AH6: 'Principal Expert Emeritus Professor – Sports',
  AH7: 'Professor – 1st Class, Physical & Sports Activities',
  AH8: 'Professor – Higher Class, Physical & Sports Activities',
  AH9: 'Emeritus Professor – Physical & Sports Activities',
  AHA: 'Expert Emeritus Professor – Physical & Sports Activities',
  AHB: 'Principal Emeritus Professor – Physical & Sports Activities',
  AHC: 'Principal Expert Emeritus Professor – PSA',
  AHD: 'Professor – 1st Class, All Sports',
  AHE: 'Professor – All Sports',
  AHF: 'Professor – Higher Class, All Sports',
  AHG: 'Emeritus Professor – All Sports',
  AHH: 'Expert Emeritus Professor – All Sports',
  AHI: 'Principal Professor – All Sports',
  AHJ: 'Principal Professor Higher Class – All Sports',
  AHK: 'Principal Emeritus Professor – All Sports',
  AHL: 'Principal Expert Emeritus Professor – All Sports',
  AHM: 'General Inspector – Expert Sports Activities',
  AHN: 'General Inspector – Sports Activities',
  AHO: 'Principal Inspector – Sports Activities',
  AHP: 'Physical Education Inspector – Sports',
  AHQ: 'General Emeritus Inspector – Physical & Sports Education',
  AHR: 'General Inspector – Physical & Sports Education',
  AHS: 'Principal Inspector – Physical & Sports Education',
  AHT: 'Physical Education Inspector – Sports & Education',
  AHU: 'General Inspector – Expert Sports',
  AHV: 'General Sports Inspector',
  AHW: 'Principal Sports Inspector',
  AHX: 'Sports Inspector',
  // ── AI series (Youth and Childhood inspectors) ────────────────────────────
  AI1: 'Youth and Childhood Inspector',
  AI2: 'Principal Inspector – Youth and Childhood',
  AI3: 'General Inspector – Youth and Childhood',
  AI4: 'General Expert Inspector – Youth and Childhood',
  // ── AX series (Military Medical – Principal rank variants) ────────────────
  AX0: 'Lieutenant Colonel – Veterinary Surgeon',
  AX1: 'Colonel Major – Dental Surgeon (P)',
  AX2: 'Colonel – Physician (P)',
  AX3: 'Colonel – Vet. Surgeon',
  AX4: 'Colonel – Pharmacist (P)',
  AX5: 'Colonel – Dental Surgeon (P)',
  AX6: 'Lieutenant Colonel – Physician (P)',
  AX8: 'Lieutenant Colonel – Pharmacist',
  AX9: 'Lieutenant Colonel – Dental Surgeon',
  AXC: 'Commander – Physician (P)',
  AXE: 'Commander – Vet. Surgeon (P)',
  AXF: 'Commander – Pharmacist (P)',
  AXH: 'Commander – Dental Surgeon',
  AXP: 'Lieutenant – Vet. Surgeon',
  AXQ: 'Lieutenant – Pharmacist',
  AXR: 'Lieutenant – Dental Surgeon',
  AXS: 'Captain – Physician (P)',
  AXT: 'Captain – Vet. Surgeon',
  AXU: 'Captain – Pharmacist (P)',
  AXV: 'Captain – Dental Surgeon',
  // ── AY series (Military Medical – General ranks, variants) ────────────────
  AYA: 'General Corps – Vet. Surgeon',
  AYC: 'Brigadier General – Physician (P)',
  AYD: 'Brigadier General – Vet. Surgeon',
  AYE: 'Brigadier General – Pharmacist',
  AYF: 'Brigadier General – Dental Surgeon',
  AYG: 'General Corps – Physician (P)',
  AYR: 'General Corps – Pharmacist',
  AYS: 'General Corps – Dental Surgeon',
  AYT: 'Major General – Physician',
  AYU: 'Major General – Vet. Surgeon',
  AYV: 'Major General – Pharmacist',
  AYW: 'Major General – Dental Surgeon',
  AYX: 'Colonel Major – Physician (P)',
  AYY: 'Colonel Major – Vet. Surgeon',
  AYZ: 'Colonel Major – Pharmacist',
  // ── B series (Paramedical / Education / Admin variants) ───────────────────
  B01: 'Principal Emeritus Professor – Paramedical (Expert Class)',
  B02: 'Principal Emeritus Professor – Paramedical',
  B03: 'Emeritus Professor (Expert Class) – Paramedical',
  B04: 'Emeritus Professor – Paramedical',
  B05: 'Technician General',
  B06: 'Chief Principal Technician',
  B07: 'Emeritus Professor – Physical Education (Expert Class)',
  B08: 'Emeritus Professor – Cultural Animation',
  B10: 'Lieutenant of the Ship',
  B11: 'Captain – Physician',
  B12: 'Captain – Vet. Surgeon',
  B13: 'Captain – Magistrate 1st Grade',
  B14: 'Captain – Pharmacist',
  B15: 'Captain – Dental Surgeon',
  B16: 'Captain – University Hospital Assistant',
  B17: 'Captain – University Hospital Pharmacy Assistant',
  B18: 'Lieutenant A1',
  B19: 'Ensign 1st Class',
  B20: 'Principal Professor (Higher Class) – Paramedical Education',
  B21: 'Principal Professor – Paramedical Education',
  B22: 'Professor (Higher Class) – Paramedical Education',
  B23: 'Contract Employee (635 TND)',
  B25: 'General Inspector – Paramedical Education',
  B26: 'Principal Inspector – Paramedical Education',
  B27: 'Contract Part-time Assistant',
  B28: 'Inspector – Physical Education & Sports',
  B29: 'Inspector – Youth and Childhood',
  B30: 'Contract Employee (1,761.5 TND)',
  B31: 'Lieutenant – Vet. Surgeon A1',
  B32: 'Lieutenant – Magistrate 1st Grade A1',
  B33: 'Lieutenant – Pharmacist Cat. A1',
  B34: 'Lieutenant – Dental Surgeon A1',
  B35: 'General Supervisor Chief (Higher Class)',
  B36: 'Chief General Supervisor',
  B37: 'Principal General Supervisor (Higher Class)',
  B38: 'Principal General Supervisor',
  B39: 'General Supervisor',
  B40: 'Physical Education Teacher – Primary School',
  B41: 'Principal Application Master – PE',
  B42: 'Principal Master – Physical Education',
  B43: 'Principal Sports Animator',
  B44: 'Emeritus Professor – Primary Schools',
  B45: 'Principal Professor (Higher Class) – Primary Schools',
  B46: 'Principal Professor – Primary Schools',
  B47: 'Principal Application Master (Higher Class)',
  B48: 'Principal Agrégé Professor – Emeritus',
  B49: 'Chief Principal General Supervisor',
  B50: 'General Inspector – Labour Conciliation',
  B51: 'Chief Inspector – Labour Conciliation',
  B52: 'Central Inspector – Labour Conciliation',
  B53: 'Labour Conciliator Inspector',
  B54: 'Principal Counselor Supervisor A1',
  B55: 'Counselor Supervisor A1',
  B56: 'Principal Supervisor (Higher Class)',
  B57: 'Principal Supervisor A2',
  B58: 'Supervisor A3',
  B59: 'Principal Emeritus Professor',
  B60: 'Pharmacy Intern',
  B61: 'Major Specialist Physician – PH',
  B62: 'Emeritus Professor – Cultural Animation',
  B63: 'Expert Class Emeritus Professor – Cultural Animation',
  B64: 'Principal Emeritus Professor – Cultural Animation',
  B65: 'Principal Professor (Higher Class) – Cultural Animation',
  B66: 'Principal Professor – Cultural Animation',
  B67: 'Professor (Higher Class) – Cultural Animation',
  B68: 'Professor – Cultural Animation',
  B69: 'Deputy Professor – Cultural Animation',
  B70: 'Controller General – Public Expenditure',
  B71: 'Chief Controller – Public Expenditure',
  B72: 'Principal Controller – Public Expenditure',
  B73: 'Controller – Public Expenditure',
  B74: 'Deputy Controller – Public Expenditure',
  B75: 'Attaché Controller – Public Expenditure',
  B76: 'Secretary Controller – Public Expenditure',
  B77: 'Clerk – Public Expenditure Control',
  B79: 'Principal Professor – Exceptional Class (Conciliation Courts)',
  B80: 'Principal Emeritus Professor',
  B81: 'Emeritus Professor – Secondary Education',
  B82: 'Administrator General – Education',
  B83: 'Chief Administrator – Education',
  B84: 'Senior Administrator – Education',
  B85: 'Administrator – Education',
  B86: 'Deputy Administrator – Education',
  B87: 'Administrative Secretary – Education',
  B88: 'Administrative Clerk – Education',
  B89: 'Reception Agent – Education',
  B90: 'General Inspector – Economic Control',
  B91: 'Chief Inspector – Economic Control',
  B92: 'Central Inspector – Economic Control',
  B93: 'Inspector – Economic Control',
  B94: 'Attaché Inspector – Economic Control',
  B95: 'Economic Control Agent',
  B96: 'General Nurse – PH',
  B97: 'Major Principal Nurse',
  B98: 'General Superior Technician – PH',
  B99: 'Major Principal Superior Technician',
  BA1: 'General Bailiff – Treasury',
  BA2: 'Chief Bailiff – Treasury',
  BA3: 'Central Bailiff – Treasury',
  BA4: 'Principal Bailiff – Treasury',
  BA5: 'Treasury Bailiff',
  BA6: 'Presidential Researcher',
  BA7: 'Principal Researcher',
  BA8: 'Researcher',
  BA9: 'Research Attaché',
  BAA: 'Controller General – State',
  BAB: 'Chief Controller – State',
  BAC: 'State Controller',
  BAD: 'Deputy Controller – State',
  BAE: 'Controller General – Public Procurement',
  BAF: 'Chief Controller – Public Procurement',
  BAG: 'Controller – Public Procurement',
  BAH: 'Deputy Controller – Public Procurement',
  BAI: 'Chief Practitioner Counselor (Higher Class)',
  BAJ: 'Education Chief Practitioner Counselor',
  BAK: 'Practitioner Counselor (Higher Class)',
  BAL: 'Principal Practitioner Counselor',
  BAM: 'Education Practitioner Counselor',
  BAN: 'Deputy Education Practitioner Counselor',
  BAP: 'Chief Inspector – Social Education',
  BAQ: 'Principal Inspector – Social Education',
  BAR: 'Social Education Inspector',
  BAS: 'General Inspector – Labour',
  BAT: 'Chief Inspector – Labour',
  BAU: 'Central Inspector – Labour',
  BAV: 'Labour Inspector',
  BAW: 'Principal Special Educator (Higher Class)',
  BAX: 'Principal Special Educator',
  BAY: 'Emeritus Chief Practitioner Counselor',
  BAZ: 'Principal Emeritus Practitioner Counselor (Higher Class)',
  BB1: 'Principal Professor – Social Education',
  BB2: 'Professor – Social Education',
  BB3: 'Master Apprentice – Principal, Higher Class, Social Ed.',
  BB4: 'Master Apprentice – Principal, Social Education',
  BB5: 'Master Apprentice – Social Education',
  BB6: 'Principal Master – Social Education',
  BB7: 'Emeritus Professor (Higher Class) – Primary Education',
  BB8: 'Professor (Higher Class) – Primary Schools',
  BBA: 'Warrant Officer – Customs',
  BBB: 'Sergeant Major – Customs',
  BBC: 'Sergeant – Customs',
  BBD: 'Administrator General – Higher Education',
  BBE: 'Chief Administrator – Higher Education',
  BBF: 'Senior Administrator – Higher Education',
  BBG: 'Administrator – Higher Education',
  BBH: 'Attaché – Higher Education',
  BBI: 'Secretary – Higher Education',
  BBJ: 'Clerk – Higher Education',
  BBK: 'Reception Agent – Higher Education',
  BBL: 'Chief Assistant (Higher Class) – ESRS',
  BBM: 'Chief Research Application Assistant',
  BBN: 'Principal Assistant (Higher Class) – ESRS',
  BBP: 'Application Assistant – ESRS',
  BBQ: 'Application Assistant – ESRS',
  BBR: 'Application Research Preparer – ESRS',
  BBS: 'Principal Emeritus Preacher',
  BBT: 'Principal Application Initiator',
  BBU: 'Principal Expert Class Professor',
  BBV: 'Principal Professor (Emeritus Expert Class)',
  BBW: 'Emeritus Professor (Expert Class) – Physical Education',
  BBX: 'Principal Agrégé Professor (Higher Class)',
  BBZ: 'Contract Employee – ISET',
  BC1: 'Principal Emeritus Professor – Primary Schools',
  BC2: 'Emeritus Professor – Physical Education',
  BC3: 'Emeritus Professor – Primary Schools',
  BC4: 'Principal Professor (Higher Class) – Primary Schools',
  BC5: 'Principal Professor – Primary Schools, Physical Ed.',
  BC6: 'Principal Application Master (Higher Class) – Physical Ed.',
  BC7: 'Principal Emeritus Professor – Youth and Childhood',
  BC8: 'Emeritus Professor – Youth and Childhood',
  BC9: 'Principal Application Master A2 – Physical Ed.',
  BCA: 'Lieutenant – Military Education Assistant',
  BCB: 'Captain – Military Education Assistant',
  BCC: 'Commander – Military Education Assistant',
  BCD: 'Lieutenant Colonel – Military Education Assistant',
  BCE: 'Colonel – Military Education Assistant',
  BCF: 'Colonel Major – Military Education Assistant',
  BCG: 'Administrator General – Ministry of Interior',
  BCH: 'Chief Administrator – Ministry of Interior',
  BCI: 'Senior Administrator – Ministry of Interior',
  BCJ: 'Administrator – Ministry of Interior',
  BCK: 'Deputy Administrator – Ministry of Interior',
  BCL: 'Administrative Secretary – Ministry of Interior',
  BCM: 'Administrative Clerk – Ministry of Interior',
  BCN: 'Reception Agent – Ministry of Interior',
  BCP: 'Professor (Higher Class) – Physical Education, Primary Schools',
};
