CREATE SCHEMA IF NOT EXISTS staging;

DROP TABLE IF EXISTS staging.stg_paie2015;
CREATE TABLE staging.stg_paie2015 (
    pa_codmin text,
    pa_mat text,
    pa_mois integer,
    pa_annee integer,
    pa_type text,
    pa_sec integer,
    pa_noml text,
    pa_prenl text,
    pa_sexe text,
    pa_datnais text,
    pa_datent text,
    pa_adrl text,
    pa_regcnr text,
    pa_capd text,
    pa_cab text,
    pa_sg text,
    pa_dg text,
    pa_dire text,
    pa_sdir text,
    pa_serv text,
    pa_unite text,
    pa_loca text,
    pa_article text,
    pa_parag text,
    pa_mp text,
    pa_idbank text,
    pa_grd text,
    pa_eche integer,
    pa_date_ech text,
    pa_nbrfam text,
    pa_enfits integer,
    pa_totinf integer,
    pa_codconj text,
    pa_sitfam text,
    pa_efonc text,
    pa_fonc text,
    pa_indice numeric(18,6),
    pa_natu text,
    pa_datnatu text,
    pa_mutuel text,
    pa_typarmee text,
    pa_salimp numeric(18,6),
    pa_salnimp numeric(18,6),
    pa_avkm numeric(18,6),
    pa_avlog numeric(18,6),
    pa_cpe numeric(18,6),
    pa_retrait numeric(18,6),
    pa_cps numeric(18,6),
    pa_capdeces numeric(18,6),
    pa_netord numeric(18,6),
    pa_netpay numeric(18,6),
    pa_rapimp numeric(18,6),
    pa_rapni numeric(18,6),
    pa_sub numeric(18,6),
    pa_sps numeric(18,6),
    pa_spl numeric(18,6),
    pa_rapsalb numeric(18,6),
    pa_brutcnr numeric(18,6),
    pa_salbrut numeric(18,6),
    load_ts timestamptz NOT NULL DEFAULT now(),
    source_name text NOT NULL
);

DROP TABLE IF EXISTS staging.stg_ind2015;
CREATE TABLE staging.stg_ind2015 (
    pa_codmin text,
    pa_mat text,
    pa_mois integer,
    pa_annee integer,
    pa_type text,
    pa_sec integer,
    pa_noml text,
    pa_prenl text,
    pa_sexe text,
    pa_datnais text,
    pa_datent text,
    pa_adrl text,
    pa_regcnr text,
    pa_capd text,
    pa_cab text,
    pa_sg text,
    pa_dg text,
    pa_dire text,
    pa_sdir text,
    pa_serv text,
    pa_unite text,
    pa_loca text,
    pa_article text,
    pa_parag text,
    pa_mp text,
    pa_idbank text,
    pa_grd text,
    pa_eche integer,
    pa_date_ech text,
    pa_nbrfam text,
    pa_enfits integer,
    pa_totinf integer,
    pa_codconj text,
    pa_sitfam text,
    pa_efonc text,
    pa_fonc text,
    pa_indice numeric(18,6),
    pa_natu text,
    pa_datnatu text,
    pa_mutuel text,
    pa_typarmee text,
    pa_salimp numeric(18,6),
    pa_salnimp numeric(18,6),
    pa_avkm numeric(18,6),
    pa_avlog numeric(18,6),
    pa_cpe numeric(18,6),
    pa_retrait numeric(18,6),
    pa_cps numeric(18,6),
    pa_capdeces numeric(18,6),
    pa_netord numeric(18,6),
    pa_netpay numeric(18,6),
    pa_rapimp numeric(18,6),
    pa_rapni numeric(18,6),
    pa_sub numeric(18,6),
    pa_sps numeric(18,6),
    pa_spl numeric(18,6),
    pa_rapsalb numeric(18,6),
    pa_brutcnr numeric(18,6),
    pa_salbrut numeric(18,6),
    load_ts timestamptz NOT NULL DEFAULT now(),
    source_name text NOT NULL
);

DROP TABLE IF EXISTS staging.stg_grade;
CREATE TABLE staging.stg_grade (
    codgrd text,
    codcorps text,
    cat text,
    classgrd text,
    efonc text,
    libcgrdl text,
    libcgrda text,
    liblgrdl text,
    liblgrda text,
    agemax text,
    agemin text,
    gprom text,
    typgrd text,
    ageret text,
    defgi text,
    defgv text,
    hcorps text,
    etat_g text,
    natrem text,
    finrec text,
    fin200 text,
    nivdep text,
    load_ts timestamptz NOT NULL DEFAULT now(),
    source_name text NOT NULL
);

DROP TABLE IF EXISTS staging.stg_nature;
CREATE TABLE staging.stg_nature (
    codnat text,
    typnat text,
    libnatl text,
    libnata text,
    load_ts timestamptz NOT NULL DEFAULT now(),
    source_name text NOT NULL
);

DROP TABLE IF EXISTS staging.stg_region;
CREATE TABLE staging.stg_region (
    coddep text,
    codreg text,
    lib_reg text,
    lib_rega text,
    code_dept text,
    code_region text,
    fichier text,
    codsreg text,
    load_ts timestamptz NOT NULL DEFAULT now(),
    source_name text NOT NULL
);

DROP TABLE IF EXISTS staging.stg_organisme;
CREATE TABLE staging.stg_organisme (
    codetab text,
    cab text,
    sg text,
    dg text,
    dire text,
    sdir text,
    serv text,
    unite text,
    liborgl text,
    liborga text,
    typstruct text,
    codloc text,
    etatdorg text,
    roleorgl text,
    roleorga text,
    deleg text,
    codgouv text,
    centreg text,
    gboprg text,
    gbosprg text,
    gboact text,
    gbouo text,
    load_ts timestamptz NOT NULL DEFAULT now(),
    source_name text NOT NULL
);

DROP TABLE IF EXISTS staging.stg_indem_def;
CREATE TABLE staging.stg_indem_def (
    tmi_cind text,
    tmi_arg1 numeric(18,6),
    tmi_arg2 numeric(18,6),
    tmi_nseq numeric(18,6),
    tmi_nval numeric(18,6),
    tmi_cnr text,
    tmi_imp text,
    tmi_fil1 text,
    tmi_fil2 text,
    tmi_nat text,
    tmi_nai text,
    tmi_pflag numeric(18,6),
    tmi_dpc text,
    tmi_zon text,
    tmi_libc text,
    tmi_libl text,
    tmi_cins text,
    tmi_liba text,
    load_ts timestamptz NOT NULL DEFAULT now(),
    source_name text NOT NULL
);
