DROP TABLE IF EXISTS public.fact_paie CASCADE;
CREATE TABLE public.fact_paie (
    fact_paie_sk bigserial PRIMARY KEY,
    employee_sk bigint NOT NULL REFERENCES public.dim_employee(employee_sk),
    time_sk bigint NOT NULL REFERENCES public.dim_temps(time_sk),
    grade_sk bigint REFERENCES public.dim_grade(grade_sk),
    nature_sk bigint REFERENCES public.dim_nature(nature_sk),
    region_sk bigint REFERENCES public.dim_region(region_sk),
    organisme_sk bigint REFERENCES public.dim_organisme(organisme_sk),
    pa_mat text NOT NULL,
    pa_annee integer NOT NULL,
    pa_mois smallint NOT NULL,
    pa_type text NOT NULL,
    pa_sec integer NOT NULL DEFAULT -1,
    pa_codmin text NOT NULL DEFAULT '',
    pa_dire text NOT NULL DEFAULT '',
    pa_article text NOT NULL DEFAULT '',
    pa_parag text NOT NULL DEFAULT '',
    pa_salimp numeric(18,6),
    pa_salnimp numeric(18,6),
    pa_avkm numeric(18,6),
    pa_avlog numeric(18,6),
    pa_cpe numeric(18,6),
    pa_retrait numeric(18,6),
    pa_cps numeric(18,6),
    pa_capdeces numeric(18,6),
    pa_netord numeric(18,6),
    pa_netpay numeric(18,6),
    pa_rapimp numeric(18,6),
    pa_rapni numeric(18,6),
    pa_sub numeric(18,6),
    pa_sps numeric(18,6),
    pa_spl numeric(18,6),
    pa_rapsalb numeric(18,6),
    pa_brutcnr numeric(18,6),
    pa_salbrut numeric(18,6),
    source_name text NOT NULL,
    load_ts timestamptz NOT NULL DEFAULT now(),
    UNIQUE (pa_mat, pa_annee, pa_mois, pa_type, pa_sec, pa_codmin, pa_dire, pa_article, pa_parag)
);

DROP TABLE IF EXISTS public.fact_indemnite CASCADE;
CREATE TABLE public.fact_indemnite (
    fact_indemnite_sk bigserial PRIMARY KEY,
    employee_sk bigint NOT NULL REFERENCES public.dim_employee(employee_sk),
    time_sk bigint NOT NULL REFERENCES public.dim_temps(time_sk),
    grade_sk bigint REFERENCES public.dim_grade(grade_sk),
    nature_sk bigint REFERENCES public.dim_nature(nature_sk),
    region_sk bigint REFERENCES public.dim_region(region_sk),
    organisme_sk bigint REFERENCES public.dim_organisme(organisme_sk),
    indemnite_sk bigint REFERENCES public.dim_indemnite(indemnite_sk),
    pa_mat text NOT NULL,
    pa_annee integer NOT NULL,
    pa_mois smallint NOT NULL,
    pa_type text NOT NULL,
    pa_sec integer NOT NULL DEFAULT -1,
    pa_codmin text NOT NULL DEFAULT '',
    pa_dire text NOT NULL DEFAULT '',
    pa_article text NOT NULL DEFAULT '',
    pa_parag text NOT NULL DEFAULT '',
    pa_salimp numeric(18,6),
    pa_salnimp numeric(18,6),
    pa_avkm numeric(18,6),
    pa_avlog numeric(18,6),
    pa_cpe numeric(18,6),
    pa_retrait numeric(18,6),
    pa_cps numeric(18,6),
    pa_capdeces numeric(18,6),
    pa_netord numeric(18,6),
    pa_netpay numeric(18,6),
    pa_rapimp numeric(18,6),
    pa_rapni numeric(18,6),
    pa_sub numeric(18,6),
    pa_sps numeric(18,6),
    pa_spl numeric(18,6),
    pa_rapsalb numeric(18,6),
    pa_brutcnr numeric(18,6),
    pa_salbrut numeric(18,6),
    source_name text NOT NULL,
    load_ts timestamptz NOT NULL DEFAULT now(),
    UNIQUE (pa_mat, pa_annee, pa_mois, pa_type, pa_sec, pa_codmin, pa_dire, pa_article, pa_parag)
);
